# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/workspace/filter2d_stream/filter2d_stream.srcs/sources_1/bd/filter2D_design/ip/filter2D_design_axis_dwidth_converter_0_0/filter2D_design_axis_dwidth_converter_0_0.xci
# IP: The module: 'filter2D_design_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/filter2d_stream/filter2d_stream.gen/sources_1/bd/filter2D_design/ip/filter2D_design_axis_dwidth_converter_0_0/filter2D_design_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter2D_design_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/workspace/filter2d_stream/filter2d_stream.srcs/sources_1/bd/filter2D_design/ip/filter2D_design_axis_dwidth_converter_0_0/filter2D_design_axis_dwidth_converter_0_0.xci
# IP: The module: 'filter2D_design_axis_dwidth_converter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/filter2d_stream/filter2d_stream.gen/sources_1/bd/filter2D_design/ip/filter2D_design_axis_dwidth_converter_0_0/filter2D_design_axis_dwidth_converter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter2D_design_axis_dwidth_converter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
