// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module rgb2gray2thresh_accel_xfMat2axis_8_0_2160_3840_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_imgOutput2_data_dout,
        p_imgOutput2_data_num_data_valid,
        p_imgOutput2_data_fifo_cap,
        p_imgOutput2_data_empty_n,
        p_imgOutput2_data_read,
        imgOutput_TDATA,
        imgOutput_TVALID,
        imgOutput_TREADY,
        imgOutput_TKEEP,
        imgOutput_TSTRB,
        imgOutput_TUSER,
        imgOutput_TLAST,
        imgOutput_TID,
        imgOutput_TDEST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_imgOutput2_data_dout;
input  [1:0] p_imgOutput2_data_num_data_valid;
input  [1:0] p_imgOutput2_data_fifo_cap;
input   p_imgOutput2_data_empty_n;
output   p_imgOutput2_data_read;
output  [7:0] imgOutput_TDATA;
output   imgOutput_TVALID;
input   imgOutput_TREADY;
output  [0:0] imgOutput_TKEEP;
output  [0:0] imgOutput_TSTRB;
output  [0:0] imgOutput_TUSER;
output  [0:0] imgOutput_TLAST;
output  [0:0] imgOutput_TID;
output  [0:0] imgOutput_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_imgOutput2_data_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] i_1_reg_112;
wire    ap_CS_fsm_state2;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_done;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_idle;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_ready;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_p_imgOutput2_data_read;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TREADY;
wire   [7:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDATA;
wire    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TKEEP;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TSTRB;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TUSER;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TLAST;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TID;
wire   [0:0] grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDEST;
reg    grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg;
wire   [0:0] icmp_ln101_fu_88_p2;
wire    ap_CS_fsm_state3;
reg   [11:0] i_fu_54;
wire   [11:0] i_2_fu_94_p2;
reg    ap_block_state1;
wire    ap_CS_fsm_state4;
wire    regslice_both_imgOutput_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    imgOutput_TVALID_int_regslice;
wire    imgOutput_TREADY_int_regslice;
wire    regslice_both_imgOutput_V_data_V_U_vld_out;
wire    regslice_both_imgOutput_V_keep_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_keep_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_keep_V_U_vld_out;
wire    regslice_both_imgOutput_V_strb_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_strb_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_strb_V_U_vld_out;
wire    regslice_both_imgOutput_V_user_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_user_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_user_V_U_vld_out;
wire    regslice_both_imgOutput_V_last_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_last_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_last_V_U_vld_out;
wire    regslice_both_imgOutput_V_id_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_id_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_id_V_U_vld_out;
wire    regslice_both_imgOutput_V_dest_V_U_apdone_blk;
wire    regslice_both_imgOutput_V_dest_V_U_ack_in_dummy;
wire    regslice_both_imgOutput_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg = 1'b0;
end

rgb2gray2thresh_accel_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start),
    .ap_done(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_done),
    .ap_idle(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_idle),
    .ap_ready(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_ready),
    .p_imgOutput2_data_dout(p_imgOutput2_data_dout),
    .p_imgOutput2_data_num_data_valid(2'd0),
    .p_imgOutput2_data_fifo_cap(2'd0),
    .p_imgOutput2_data_empty_n(p_imgOutput2_data_empty_n),
    .p_imgOutput2_data_read(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_p_imgOutput2_data_read),
    .imgOutput_TREADY(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TREADY),
    .i(i_1_reg_112),
    .imgOutput_TDATA(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDATA),
    .imgOutput_TVALID(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .imgOutput_TKEEP(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TKEEP),
    .imgOutput_TSTRB(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TSTRB),
    .imgOutput_TUSER(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TUSER),
    .imgOutput_TLAST(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TLAST),
    .imgOutput_TID(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TID),
    .imgOutput_TDEST(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDEST)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_imgOutput_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDATA),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(imgOutput_TREADY_int_regslice),
    .data_out(imgOutput_TDATA),
    .vld_out(regslice_both_imgOutput_V_data_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_data_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TKEEP),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_keep_V_U_ack_in_dummy),
    .data_out(imgOutput_TKEEP),
    .vld_out(regslice_both_imgOutput_V_keep_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_keep_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TSTRB),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_strb_V_U_ack_in_dummy),
    .data_out(imgOutput_TSTRB),
    .vld_out(regslice_both_imgOutput_V_strb_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_strb_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TUSER),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_user_V_U_ack_in_dummy),
    .data_out(imgOutput_TUSER),
    .vld_out(regslice_both_imgOutput_V_user_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_user_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TLAST),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_last_V_U_ack_in_dummy),
    .data_out(imgOutput_TLAST),
    .vld_out(regslice_both_imgOutput_V_last_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_last_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TID),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_id_V_U_ack_in_dummy),
    .data_out(imgOutput_TID),
    .vld_out(regslice_both_imgOutput_V_id_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_id_V_U_apdone_blk)
);

rgb2gray2thresh_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_imgOutput_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TDEST),
    .vld_in(grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID),
    .ack_in(regslice_both_imgOutput_V_dest_V_U_ack_in_dummy),
    .data_out(imgOutput_TDEST),
    .vld_out(regslice_both_imgOutput_V_dest_V_U_vld_out),
    .ack_out(imgOutput_TREADY),
    .apdone_blk(regslice_both_imgOutput_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_imgOutput_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln101_fu_88_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_ready == 1'b1)) begin
            grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_54 <= 12'd0;
    end else if (((icmp_ln101_fu_88_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_54 <= i_2_fu_94_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_112 <= i_fu_54;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_imgOutput_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_imgOutput_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_imgOutput_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_imgOutput2_data_read = grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_p_imgOutput2_data_read;
    end else begin
        p_imgOutput2_data_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln101_fu_88_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_imgOutput_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start = grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_ap_start_reg;

assign grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TREADY = (imgOutput_TREADY_int_regslice & ap_CS_fsm_state3);

assign i_2_fu_94_p2 = (i_fu_54 + 12'd1);

assign icmp_ln101_fu_88_p2 = ((i_fu_54 == 12'd2160) ? 1'b1 : 1'b0);

assign imgOutput_TVALID = regslice_both_imgOutput_V_data_V_U_vld_out;

assign imgOutput_TVALID_int_regslice = grp_xfMat2axis_8_0_2160_3840_1_Pipeline_loop_col_mat2axi_fu_58_imgOutput_TVALID;

endmodule //rgb2gray2thresh_accel_xfMat2axis_8_0_2160_3840_1_s
