// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fast_accel_rgb2gray_16_0_3840_2160_1_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_dout,
        p_src_rows_num_data_valid,
        p_src_rows_fifo_cap,
        p_src_rows_empty_n,
        p_src_rows_read,
        p_src_cols_dout,
        p_src_cols_num_data_valid,
        p_src_cols_fifo_cap,
        p_src_cols_empty_n,
        p_src_cols_read,
        imgInput_data_dout,
        imgInput_data_num_data_valid,
        imgInput_data_fifo_cap,
        imgInput_data_empty_n,
        imgInput_data_read,
        grayin_mat_data_din,
        grayin_mat_data_num_data_valid,
        grayin_mat_data_fifo_cap,
        grayin_mat_data_full_n,
        grayin_mat_data_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_dout;
input  [1:0] p_src_rows_num_data_valid;
input  [1:0] p_src_rows_fifo_cap;
input   p_src_rows_empty_n;
output   p_src_rows_read;
input  [31:0] p_src_cols_dout;
input  [1:0] p_src_cols_num_data_valid;
input  [1:0] p_src_cols_fifo_cap;
input   p_src_cols_empty_n;
output   p_src_cols_read;
input  [23:0] imgInput_data_dout;
input  [1:0] imgInput_data_num_data_valid;
input  [1:0] imgInput_data_fifo_cap;
input   imgInput_data_empty_n;
output   imgInput_data_read;
output  [7:0] grayin_mat_data_din;
input  [1:0] grayin_mat_data_num_data_valid;
input  [1:0] grayin_mat_data_fifo_cap;
input   grayin_mat_data_full_n;
output   grayin_mat_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_rows_read;
reg p_src_cols_read;
reg imgInput_data_read;
reg grayin_mat_data_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_rows_blk_n;
reg    p_src_cols_blk_n;
wire   [15:0] height_fu_73_p1;
reg   [15:0] height_reg_116;
reg    ap_block_state1;
wire   [15:0] empty_fu_77_p1;
reg   [15:0] empty_reg_121;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_done;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_idle;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_ready;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_imgInput_data_read;
wire   [7:0] grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_din;
wire    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_write;
reg    grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln5500_fu_93_p2;
wire    ap_CS_fsm_state3;
reg   [12:0] i_fu_48;
wire   [12:0] i_4_fu_98_p2;
wire   [15:0] zext_ln5500_fu_89_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg = 1'b0;
end

fast_accel_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start),
    .ap_done(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_done),
    .ap_idle(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_idle),
    .ap_ready(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_ready),
    .imgInput_data_dout(imgInput_data_dout),
    .imgInput_data_num_data_valid(2'd0),
    .imgInput_data_fifo_cap(2'd0),
    .imgInput_data_empty_n(imgInput_data_empty_n),
    .imgInput_data_read(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_imgInput_data_read),
    .grayin_mat_data_din(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_din),
    .grayin_mat_data_num_data_valid(2'd0),
    .grayin_mat_data_fifo_cap(2'd0),
    .grayin_mat_data_full_n(grayin_mat_data_full_n),
    .grayin_mat_data_write(grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_write),
    .empty(empty_reg_121)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln5500_fu_93_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln5500_fu_93_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_ready == 1'b1)) begin
            grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_48 <= 13'd0;
    end else if (((icmp_ln5500_fu_93_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_48 <= i_4_fu_98_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_121 <= empty_fu_77_p1;
        height_reg_116 <= height_fu_73_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5500_fu_93_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5500_fu_93_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grayin_mat_data_write = grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_write;
    end else begin
        grayin_mat_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgInput_data_read = grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_imgInput_data_read;
    end else begin
        imgInput_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_blk_n = p_src_cols_empty_n;
    end else begin
        p_src_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_read = 1'b1;
    end else begin
        p_src_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_blk_n = p_src_rows_empty_n;
    end else begin
        p_src_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_read = 1'b1;
    end else begin
        p_src_rows_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln5500_fu_93_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_fu_77_p1 = p_src_cols_dout[15:0];

assign grayin_mat_data_din = grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_grayin_mat_data_din;

assign grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start = grp_rgb2gray_16_0_3840_2160_1_2_2_Pipeline_columnloop_fu_64_ap_start_reg;

assign height_fu_73_p1 = p_src_rows_dout[15:0];

assign i_4_fu_98_p2 = (i_fu_48 + 13'd1);

assign icmp_ln5500_fu_93_p2 = ((zext_ln5500_fu_89_p1 < height_reg_116) ? 1'b1 : 1'b0);

assign zext_ln5500_fu_89_p1 = i_fu_48;

endmodule //fast_accel_rgb2gray_16_0_3840_2160_1_2_2_s
