// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        grayin_mat_data_dout,
        grayin_mat_data_num_data_valid,
        grayin_mat_data_fifo_cap,
        grayin_mat_data_empty_n,
        grayin_mat_data_read,
        p_dst_data_din,
        p_dst_data_num_data_valid,
        p_dst_data_fifo_cap,
        p_dst_data_full_n,
        p_dst_data_write,
        img_height,
        img_width,
        p_threshold,
        p_image_height_c_din,
        p_image_height_c_num_data_valid,
        p_image_height_c_fifo_cap,
        p_image_height_c_full_n,
        p_image_height_c_write,
        p_image_width_c_din,
        p_image_width_c_num_data_valid,
        p_image_width_c_fifo_cap,
        p_image_width_c_full_n,
        p_image_width_c_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] grayin_mat_data_dout;
input  [1:0] grayin_mat_data_num_data_valid;
input  [1:0] grayin_mat_data_fifo_cap;
input   grayin_mat_data_empty_n;
output   grayin_mat_data_read;
output  [7:0] p_dst_data_din;
input  [1:0] p_dst_data_num_data_valid;
input  [1:0] p_dst_data_fifo_cap;
input   p_dst_data_full_n;
output   p_dst_data_write;
input  [15:0] img_height;
input  [15:0] img_width;
input  [7:0] p_threshold;
output  [15:0] p_image_height_c_din;
input  [1:0] p_image_height_c_num_data_valid;
input  [1:0] p_image_height_c_fifo_cap;
input   p_image_height_c_full_n;
output   p_image_height_c_write;
output  [15:0] p_image_width_c_din;
input  [1:0] p_image_width_c_num_data_valid;
input  [1:0] p_image_width_c_fifo_cap;
input   p_image_width_c_full_n;
output   p_image_width_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg grayin_mat_data_read;
reg p_dst_data_write;
reg p_image_height_c_write;
reg p_image_width_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_image_height_c_blk_n;
reg    p_image_width_c_blk_n;
reg    ap_block_state1;
wire   [13:0] empty_fu_315_p1;
reg   [13:0] empty_reg_758;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln526_1_fu_344_p1;
reg   [63:0] zext_ln526_1_reg_791;
wire   [2:0] trunc_ln526_fu_361_p1;
reg   [2:0] trunc_ln526_reg_799;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln526_fu_356_p2;
wire   [16:0] add_i_i66_fu_413_p2;
reg   [16:0] add_i_i66_reg_865;
wire    ap_CS_fsm_state7;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_done;
wire   [13:0] add17_i_cast_fu_419_p2;
reg   [13:0] add17_i_cast_reg_870;
wire   [16:0] sub350_i_fu_424_p2;
reg   [16:0] sub350_i_reg_875;
wire   [8:0] b0_fu_433_p2;
reg   [8:0] b0_reg_881;
wire   [2:0] trunc_ln555_fu_463_p1;
reg   [2:0] trunc_ln555_reg_886;
wire    ap_CS_fsm_state8;
wire   [2:0] trunc_ln555_1_fu_467_p1;
reg   [2:0] trunc_ln555_1_reg_891;
wire   [2:0] trunc_ln555_2_fu_471_p1;
reg   [2:0] trunc_ln555_2_reg_896;
wire   [2:0] trunc_ln555_3_fu_475_p1;
reg   [2:0] trunc_ln555_3_reg_901;
wire   [2:0] trunc_ln555_4_fu_479_p1;
reg   [2:0] trunc_ln555_4_reg_906;
wire   [2:0] trunc_ln555_5_fu_483_p1;
reg   [2:0] trunc_ln555_5_reg_911;
wire   [2:0] trunc_ln555_6_fu_487_p1;
reg   [2:0] trunc_ln555_6_reg_916;
wire   [0:0] cmp_i_i381_i_fu_504_p2;
reg   [0:0] cmp_i_i381_i_reg_924;
wire   [0:0] icmp_ln555_fu_499_p2;
wire   [0:0] cmp_i_i329_i_fu_509_p2;
reg   [0:0] cmp_i_i329_i_reg_929;
wire   [2:0] empty_44_fu_529_p1;
reg   [2:0] empty_44_reg_940;
wire   [0:0] ult_fu_533_p2;
reg   [0:0] ult_reg_945;
reg   [0:0] tmp_reg_950;
wire   [0:0] cmp_i_i253_i_1_fu_546_p2;
reg   [0:0] cmp_i_i253_i_1_reg_955;
wire   [0:0] icmp_fu_562_p2;
reg   [0:0] icmp_reg_960;
wire   [0:0] cmp_i_i253_i_3_fu_568_p2;
reg   [0:0] cmp_i_i253_i_3_reg_965;
wire   [0:0] icmp176_fu_584_p2;
reg   [0:0] icmp176_reg_970;
wire   [0:0] cmp_i_i253_i_5_fu_590_p2;
reg   [0:0] cmp_i_i253_i_5_reg_975;
wire   [0:0] cmp_i_i253_i_6_fu_596_p2;
reg   [0:0] cmp_i_i253_i_6_reg_980;
wire   [0:0] cmp_i_i73_i_not_fu_602_p2;
reg   [0:0] cmp_i_i73_i_not_reg_985;
wire   [0:0] rev177_fu_654_p2;
reg   [0:0] rev177_reg_990;
wire    ap_CS_fsm_state9;
wire   [0:0] spec_select484_fu_660_p2;
reg   [0:0] spec_select484_reg_995;
wire   [0:0] spec_select488_fu_665_p2;
reg   [0:0] spec_select488_reg_1000;
wire   [0:0] spec_select492_fu_670_p2;
reg   [0:0] spec_select492_reg_1005;
wire   [0:0] spec_select496_fu_675_p2;
reg   [0:0] spec_select496_reg_1010;
wire   [0:0] spec_select500_fu_680_p2;
reg   [0:0] spec_select500_reg_1015;
wire   [0:0] spec_select504_fu_685_p2;
reg   [0:0] spec_select504_reg_1020;
wire   [0:0] spec_select508_fu_690_p2;
reg   [0:0] spec_select508_reg_1025;
reg    buf_ce0;
wire   [7:0] buf_q0;
reg   [11:0] buf_address1;
reg    buf_ce1;
reg    buf_we1;
reg   [7:0] buf_d1;
reg    buf_1_ce0;
wire   [7:0] buf_1_q0;
reg   [11:0] buf_1_address1;
reg    buf_1_ce1;
reg    buf_1_we1;
reg   [7:0] buf_1_d1;
reg    buf_2_ce0;
wire   [7:0] buf_2_q0;
reg   [11:0] buf_2_address1;
reg    buf_2_ce1;
reg    buf_2_we1;
reg   [7:0] buf_2_d1;
reg    buf_3_ce0;
wire   [7:0] buf_3_q0;
reg   [11:0] buf_3_address1;
reg    buf_3_ce1;
reg    buf_3_we1;
reg   [7:0] buf_3_d1;
reg    buf_4_ce0;
wire   [7:0] buf_4_q0;
reg   [11:0] buf_4_address1;
reg    buf_4_ce1;
reg    buf_4_we1;
reg   [7:0] buf_4_d1;
reg    buf_5_ce0;
wire   [7:0] buf_5_q0;
reg   [11:0] buf_5_address1;
reg    buf_5_ce1;
reg    buf_5_we1;
reg   [7:0] buf_5_d1;
reg    buf_6_ce0;
wire   [7:0] buf_6_q0;
reg   [11:0] buf_6_address1;
reg    buf_6_ce1;
reg    buf_6_we1;
reg   [7:0] buf_6_d1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_done;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_idle;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_ready;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_14_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_14_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_13_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_13_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_11_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_11_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_10_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_10_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_out;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_out_ap_vld;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_done;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_idle;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_ready;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_grayin_mat_data_read;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_d1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_idle;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_ready;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_d1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_done;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_idle;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_grayin_mat_data_read;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_din;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_write;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_d1;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address0;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce0;
wire   [11:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce1;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_we1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_d1;
wire   [7:0] grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o;
wire    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld;
reg    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg;
reg    ap_block_state1_ignore_call32;
wire    ap_CS_fsm_state2;
reg    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [7:0] p_0_0_010842_lcssa550_fu_172;
reg   [63:0] init_buf_fu_112;
wire   [63:0] add_ln526_fu_366_p2;
wire   [63:0] zext_ln526_fu_340_p1;
reg   [12:0] row_fu_176;
wire   [12:0] row_5_fu_608_p2;
reg   [12:0] row_ind_fu_180;
reg   [12:0] row_ind_19_fu_184;
reg   [12:0] row_ind_20_fu_188;
reg   [12:0] row_ind_21_fu_192;
reg   [12:0] row_ind_22_fu_196;
reg   [12:0] row_ind_23_fu_200;
reg   [12:0] row_ind_24_fu_204;
wire   [16:0] conv3_i_i_i61_fu_410_p1;
wire   [8:0] p_threshold_cast_fu_430_p1;
wire   [16:0] zext_ln555_1_fu_495_p1;
wire   [15:0] zext_ln555_fu_491_p1;
wire  signed [16:0] sub_i_i297_i_fu_514_p2;
wire  signed [17:0] sub_i_i297_i_cast_fu_519_p1;
wire   [17:0] sub_i273_i_fu_523_p2;
wire   [16:0] tmp_1_fu_552_p4;
wire   [15:0] tmp_2_fu_574_p4;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg = 1'b0;
end

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address0),
    .ce0(buf_ce0),
    .q0(buf_q0),
    .address1(buf_address1),
    .ce1(buf_ce1),
    .we1(buf_we1),
    .d1(buf_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address0),
    .ce0(buf_1_ce0),
    .q0(buf_1_q0),
    .address1(buf_1_address1),
    .ce1(buf_1_ce1),
    .we1(buf_1_we1),
    .d1(buf_1_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address0),
    .ce0(buf_2_ce0),
    .q0(buf_2_q0),
    .address1(buf_2_address1),
    .ce1(buf_2_ce1),
    .we1(buf_2_we1),
    .d1(buf_2_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address0),
    .ce0(buf_3_ce0),
    .q0(buf_3_q0),
    .address1(buf_3_address1),
    .ce1(buf_3_ce1),
    .we1(buf_3_we1),
    .d1(buf_3_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address0),
    .ce0(buf_4_ce0),
    .q0(buf_4_q0),
    .address1(buf_4_address1),
    .ce1(buf_4_ce1),
    .we1(buf_4_we1),
    .d1(buf_4_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address0),
    .ce0(buf_5_ce0),
    .q0(buf_5_q0),
    .address1(buf_5_address1),
    .ce1(buf_5_ce1),
    .we1(buf_5_we1),
    .d1(buf_5_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2160 ),
    .AddressWidth( 12 ))
buf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address0),
    .ce0(buf_6_ce0),
    .q0(buf_6_q0),
    .address1(buf_6_address1),
    .ce1(buf_6_ce1),
    .we1(buf_6_we1),
    .d1(buf_6_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start),
    .ap_done(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_done),
    .ap_idle(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_idle),
    .ap_ready(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_ready),
    .row_ind_15_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out),
    .row_ind_15_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out_ap_vld),
    .row_ind_14_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_14_out),
    .row_ind_14_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_14_out_ap_vld),
    .row_ind_13_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_13_out),
    .row_ind_13_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_13_out_ap_vld),
    .row_ind_12_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out),
    .row_ind_12_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out_ap_vld),
    .row_ind_11_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_11_out),
    .row_ind_11_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_11_out_ap_vld),
    .row_ind_10_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_10_out),
    .row_ind_10_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_10_out_ap_vld),
    .row_ind_out(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_out),
    .row_ind_out_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_out_ap_vld)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start),
    .ap_done(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_done),
    .ap_idle(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_idle),
    .ap_ready(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_ready),
    .grayin_mat_data_dout(grayin_mat_data_dout),
    .grayin_mat_data_num_data_valid(2'd0),
    .grayin_mat_data_fifo_cap(2'd0),
    .grayin_mat_data_empty_n(grayin_mat_data_empty_n),
    .grayin_mat_data_read(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_grayin_mat_data_read),
    .img_width(img_width),
    .buf_6_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_address1),
    .buf_6_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_ce1),
    .buf_6_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_we1),
    .buf_6_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_d1),
    .buf_5_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_address1),
    .buf_5_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_ce1),
    .buf_5_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_we1),
    .buf_5_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_d1),
    .buf_4_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_address1),
    .buf_4_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_ce1),
    .buf_4_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_we1),
    .buf_4_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_d1),
    .buf_3_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_address1),
    .buf_3_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_ce1),
    .buf_3_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_we1),
    .buf_3_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_d1),
    .buf_2_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_address1),
    .buf_2_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_ce1),
    .buf_2_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_we1),
    .buf_2_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_d1),
    .buf_1_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_address1),
    .buf_1_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_ce1),
    .buf_1_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_we1),
    .buf_1_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_d1),
    .buf_r_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_address1),
    .buf_r_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_ce1),
    .buf_r_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_we1),
    .buf_r_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_d1),
    .trunc_ln3(trunc_ln526_reg_799)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3 grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start),
    .ap_done(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_done),
    .ap_idle(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_idle),
    .ap_ready(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_ready),
    .img_width(img_width),
    .buf_r_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_address1),
    .buf_r_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_ce1),
    .buf_r_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_we1),
    .buf_r_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_d1),
    .buf_1_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_address1),
    .buf_1_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_ce1),
    .buf_1_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_we1),
    .buf_1_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_d1),
    .buf_2_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_address1),
    .buf_2_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_ce1),
    .buf_2_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_we1),
    .buf_2_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_d1)
);

fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start),
    .ap_done(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_done),
    .ap_idle(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_idle),
    .ap_ready(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready),
    .grayin_mat_data_dout(grayin_mat_data_dout),
    .grayin_mat_data_num_data_valid(2'd0),
    .grayin_mat_data_fifo_cap(2'd0),
    .grayin_mat_data_empty_n(grayin_mat_data_empty_n),
    .grayin_mat_data_read(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_grayin_mat_data_read),
    .p_dst_data_din(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_din),
    .p_dst_data_num_data_valid(2'd0),
    .p_dst_data_fifo_cap(2'd0),
    .p_dst_data_full_n(p_dst_data_full_n),
    .p_dst_data_write(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_write),
    .add17_i_cast(add17_i_cast_reg_870),
    .buf_6_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address0),
    .buf_6_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce0),
    .buf_6_q0(buf_6_q0),
    .buf_6_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address1),
    .buf_6_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce1),
    .buf_6_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_we1),
    .buf_6_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_d1),
    .buf_r_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address0),
    .buf_r_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .buf_r_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address1),
    .buf_r_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce1),
    .buf_r_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_we1),
    .buf_r_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_d1),
    .buf_1_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address0),
    .buf_1_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce0),
    .buf_1_q0(buf_1_q0),
    .buf_1_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address1),
    .buf_1_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce1),
    .buf_1_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_we1),
    .buf_1_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_d1),
    .buf_2_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address0),
    .buf_2_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce0),
    .buf_2_q0(buf_2_q0),
    .buf_2_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address1),
    .buf_2_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce1),
    .buf_2_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_we1),
    .buf_2_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_d1),
    .buf_3_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address0),
    .buf_3_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce0),
    .buf_3_q0(buf_3_q0),
    .buf_3_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address1),
    .buf_3_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce1),
    .buf_3_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_we1),
    .buf_3_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_d1),
    .buf_4_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address0),
    .buf_4_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce0),
    .buf_4_q0(buf_4_q0),
    .buf_4_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address1),
    .buf_4_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce1),
    .buf_4_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_we1),
    .buf_4_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_d1),
    .buf_5_address0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address0),
    .buf_5_ce0(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce0),
    .buf_5_q0(buf_5_q0),
    .buf_5_address1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address1),
    .buf_5_ce1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce1),
    .buf_5_we1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_we1),
    .buf_5_d1(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_d1),
    .row_ind_30(trunc_ln555_6_reg_916),
    .row_ind_29(trunc_ln555_5_reg_911),
    .row_ind_28(trunc_ln555_4_reg_906),
    .row_ind_27(trunc_ln555_3_reg_901),
    .row_ind_26(trunc_ln555_2_reg_896),
    .row_ind_25(trunc_ln555_1_reg_891),
    .row_ind_24(trunc_ln555_reg_886),
    .sub_i273_i_cast(empty_44_reg_940),
    .spec_select484(spec_select484_reg_995),
    .spec_select488(spec_select488_reg_1000),
    .spec_select492(spec_select492_reg_1005),
    .spec_select496(spec_select496_reg_1010),
    .spec_select500(spec_select500_reg_1015),
    .spec_select504(spec_select504_reg_1020),
    .spec_select508(spec_select508_reg_1025),
    .cmp_i_i73_i_not(cmp_i_i73_i_not_reg_985),
    .p_threshold_cast(p_threshold),
    .b0(b0_reg_881),
    .p_threshold(p_threshold),
    .img_width(img_width),
    .cmp_i_i49_i(rev177_reg_990),
    .cmp_i_i381_i(cmp_i_i381_i_reg_924),
    .p_0_0_01084242_out_i(p_0_0_010842_lcssa550_fu_172),
    .p_0_0_01084242_out_o(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o),
    .p_0_0_01084242_out_o_ap_vld(grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg <= 1'b0;
    end else begin
        if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd1))) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        init_buf_fu_112 <= zext_ln526_fu_340_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd1))) begin
        init_buf_fu_112 <= add_ln526_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_fu_176 <= 13'd3;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_fu_176 <= row_5_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_19_fu_184 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_10_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_19_fu_184 <= row_ind_20_fu_188;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_20_fu_188 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_11_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_20_fu_188 <= row_ind_21_fu_192;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_21_fu_192 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_21_fu_192 <= row_ind_22_fu_196;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_22_fu_196 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_13_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_22_fu_196 <= row_ind_23_fu_200;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_23_fu_200 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_14_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_23_fu_200 <= row_ind_24_fu_204;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_24_fu_204 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_24_fu_204 <= row_ind_fu_180;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
        row_ind_fu_180 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_out;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        row_ind_fu_180 <= row_ind_19_fu_184;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_done == 1'b1))) begin
        add17_i_cast_reg_870 <= add17_i_cast_fu_419_p2;
        add_i_i66_reg_865 <= add_i_i66_fu_413_p2;
        b0_reg_881 <= b0_fu_433_p2;
        sub350_i_reg_875 <= sub350_i_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd1))) begin
        cmp_i_i253_i_1_reg_955 <= cmp_i_i253_i_1_fu_546_p2;
        cmp_i_i253_i_3_reg_965 <= cmp_i_i253_i_3_fu_568_p2;
        cmp_i_i253_i_5_reg_975 <= cmp_i_i253_i_5_fu_590_p2;
        cmp_i_i253_i_6_reg_980 <= cmp_i_i253_i_6_fu_596_p2;
        cmp_i_i329_i_reg_929 <= cmp_i_i329_i_fu_509_p2;
        cmp_i_i381_i_reg_924 <= cmp_i_i381_i_fu_504_p2;
        cmp_i_i73_i_not_reg_985 <= cmp_i_i73_i_not_fu_602_p2;
        empty_44_reg_940 <= empty_44_fu_529_p1;
        icmp176_reg_970 <= icmp176_fu_584_p2;
        icmp_reg_960 <= icmp_fu_562_p2;
        tmp_reg_950 <= sub_i273_i_fu_523_p2[32'd17];
        ult_reg_945 <= ult_fu_533_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_758 <= empty_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        p_0_0_010842_lcssa550_fu_172 <= grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        rev177_reg_990 <= rev177_fu_654_p2;
        spec_select484_reg_995 <= spec_select484_fu_660_p2;
        spec_select488_reg_1000 <= spec_select488_fu_665_p2;
        spec_select492_reg_1005 <= spec_select492_fu_670_p2;
        spec_select496_reg_1010 <= spec_select496_fu_675_p2;
        spec_select500_reg_1015 <= spec_select500_fu_680_p2;
        spec_select504_reg_1020 <= spec_select504_fu_685_p2;
        spec_select508_reg_1025 <= spec_select508_fu_690_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd1))) begin
        trunc_ln526_reg_799 <= trunc_ln526_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln555_1_reg_891 <= trunc_ln555_1_fu_467_p1;
        trunc_ln555_2_reg_896 <= trunc_ln555_2_fu_471_p1;
        trunc_ln555_3_reg_901 <= trunc_ln555_3_fu_475_p1;
        trunc_ln555_4_reg_906 <= trunc_ln555_4_fu_479_p1;
        trunc_ln555_5_reg_911 <= trunc_ln555_5_fu_483_p1;
        trunc_ln555_6_reg_916 <= trunc_ln555_6_fu_487_p1;
        trunc_ln555_reg_886 <= trunc_ln555_fu_463_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln526_1_reg_791[12 : 0] <= zext_ln526_1_fu_344_p1[12 : 0];
    end
end

always @ (*) begin
    if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_1_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_1_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_address1;
    end else begin
        buf_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_1_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce0;
    end else begin
        buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_1_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_1_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_ce1;
    end else begin
        buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_1_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_1_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_d1;
    end else begin
        buf_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_1_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_1_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_1_we1;
    end else begin
        buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_2_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_2_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_address1;
    end else begin
        buf_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_2_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce0;
    end else begin
        buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_2_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_2_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_ce1;
    end else begin
        buf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_2_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_d1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_2_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_d1;
    end else begin
        buf_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_2_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_2_we1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_2_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_2_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_2_we1;
    end else begin
        buf_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_3_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_address1;
    end else begin
        buf_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_3_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce0;
    end else begin
        buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_3_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_ce1;
    end else begin
        buf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_3_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_d1;
    end else begin
        buf_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_3_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_3_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_3_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_3_we1;
    end else begin
        buf_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_4_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_address1;
    end else begin
        buf_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_4_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce0;
    end else begin
        buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_4_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_ce1;
    end else begin
        buf_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_4_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_d1;
    end else begin
        buf_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_4_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_4_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_4_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_4_we1;
    end else begin
        buf_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_5_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_address1;
    end else begin
        buf_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_5_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce0;
    end else begin
        buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_5_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_ce1;
    end else begin
        buf_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_5_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_d1;
    end else begin
        buf_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_5_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_5_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_5_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_5_we1;
    end else begin
        buf_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_6_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_address1;
    end else begin
        buf_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_6_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce0;
    end else begin
        buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_6_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_ce1;
    end else begin
        buf_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_6_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_d1;
    end else begin
        buf_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_6_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_6_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_6_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_6_we1;
    end else begin
        buf_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_address1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_address1;
    end else begin
        buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_ce0 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce0;
    end else begin
        buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_ce1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_ce1;
    end else begin
        buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_d1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_d1;
    end else begin
        buf_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_buf_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_buf_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_we1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_buf_r_we1;
    end else begin
        buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grayin_mat_data_read = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_grayin_mat_data_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grayin_mat_data_read = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_grayin_mat_data_read;
    end else begin
        grayin_mat_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_dst_data_write = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_write;
    end else begin
        p_dst_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_c_blk_n = p_image_height_c_full_n;
    end else begin
        p_image_height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_c_write = 1'b1;
    end else begin
        p_image_height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_c_blk_n = p_image_width_c_full_n;
    end else begin
        p_image_width_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_c_write = 1'b1;
    end else begin
        p_image_width_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln526_fu_356_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln555_fu_499_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add17_i_cast_fu_419_p2 = (empty_reg_758 + 14'd3);

assign add_i_i66_fu_413_p2 = (conv3_i_i_i61_fu_410_p1 + 17'd3);

assign add_ln526_fu_366_p2 = (init_buf_fu_112 + 64'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call32 = ((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign b0_fu_433_p2 = (9'd0 - p_threshold_cast_fu_430_p1);

assign cmp_i_i253_i_1_fu_546_p2 = (($signed(sub_i273_i_fu_523_p2) < $signed(18'd1)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_3_fu_568_p2 = (($signed(sub_i273_i_fu_523_p2) < $signed(18'd3)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_5_fu_590_p2 = (($signed(sub_i273_i_fu_523_p2) < $signed(18'd5)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_6_fu_596_p2 = (($signed(sub_i_i297_i_fu_514_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign cmp_i_i329_i_fu_509_p2 = (($signed(sub350_i_reg_875) < $signed(zext_ln555_1_fu_495_p1)) ? 1'b1 : 1'b0);

assign cmp_i_i381_i_fu_504_p2 = ((zext_ln555_fu_491_p1 < img_height) ? 1'b1 : 1'b0);

assign cmp_i_i73_i_not_fu_602_p2 = ((row_fu_176 < 13'd6) ? 1'b1 : 1'b0);

assign conv3_i_i_i61_fu_410_p1 = img_height;

assign empty_44_fu_529_p1 = sub_i273_i_fu_523_p2[2:0];

assign empty_fu_315_p1 = img_width[13:0];

assign grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg;

assign grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_ap_start_reg;

assign grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_530_2_fu_253_ap_start_reg;

assign grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_541_3_fu_268_ap_start_reg;

assign icmp176_fu_584_p2 = (($signed(tmp_2_fu_574_p4) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_fu_562_p2 = (($signed(tmp_1_fu_552_p4) < $signed(17'd1)) ? 1'b1 : 1'b0);

assign icmp_ln526_fu_356_p2 = ((init_buf_fu_112 < zext_ln526_1_reg_791) ? 1'b1 : 1'b0);

assign icmp_ln555_fu_499_p2 = ((zext_ln555_1_fu_495_p1 < add_i_i66_reg_865) ? 1'b1 : 1'b0);

assign p_dst_data_din = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data_din;

assign p_image_height_c_din = img_height;

assign p_image_width_c_din = img_width;

assign p_threshold_cast_fu_430_p1 = p_threshold;

assign rev177_fu_654_p2 = (ult_reg_945 ^ 1'd1);

assign row_5_fu_608_p2 = (row_fu_176 + 13'd1);

assign spec_select484_fu_660_p2 = (tmp_reg_950 & cmp_i_i329_i_reg_929);

assign spec_select488_fu_665_p2 = (cmp_i_i329_i_reg_929 & cmp_i_i253_i_1_reg_955);

assign spec_select492_fu_670_p2 = (icmp_reg_960 & cmp_i_i329_i_reg_929);

assign spec_select496_fu_675_p2 = (cmp_i_i329_i_reg_929 & cmp_i_i253_i_3_reg_965);

assign spec_select500_fu_680_p2 = (icmp176_reg_970 & cmp_i_i329_i_reg_929);

assign spec_select504_fu_685_p2 = (cmp_i_i329_i_reg_929 & cmp_i_i253_i_5_reg_975);

assign spec_select508_fu_690_p2 = (cmp_i_i329_i_reg_929 & cmp_i_i253_i_6_reg_980);

assign start_out = real_start;

assign sub350_i_fu_424_p2 = ($signed(conv3_i_i_i61_fu_410_p1) + $signed(17'd131071));

assign sub_i273_i_fu_523_p2 = ($signed(18'd6) - $signed(sub_i_i297_i_cast_fu_519_p1));

assign sub_i_i297_i_cast_fu_519_p1 = sub_i_i297_i_fu_514_p2;

assign sub_i_i297_i_fu_514_p2 = (zext_ln555_1_fu_495_p1 - sub350_i_reg_875);

assign tmp_1_fu_552_p4 = {{sub_i273_i_fu_523_p2[17:1]}};

assign tmp_2_fu_574_p4 = {{sub_i273_i_fu_523_p2[17:2]}};

assign trunc_ln526_fu_361_p1 = init_buf_fu_112[2:0];

assign trunc_ln555_1_fu_467_p1 = row_ind_19_fu_184[2:0];

assign trunc_ln555_2_fu_471_p1 = row_ind_20_fu_188[2:0];

assign trunc_ln555_3_fu_475_p1 = row_ind_21_fu_192[2:0];

assign trunc_ln555_4_fu_479_p1 = row_ind_22_fu_196[2:0];

assign trunc_ln555_5_fu_483_p1 = row_ind_23_fu_200[2:0];

assign trunc_ln555_6_fu_487_p1 = row_ind_24_fu_204[2:0];

assign trunc_ln555_fu_463_p1 = row_ind_fu_180[2:0];

assign ult_fu_533_p2 = ((zext_ln555_fu_491_p1 < img_height) ? 1'b1 : 1'b0);

assign zext_ln526_1_fu_344_p1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_15_out;

assign zext_ln526_fu_340_p1 = grp_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3_Pipeline_VITIS_LOOP_515_1_fu_242_row_ind_12_out;

assign zext_ln555_1_fu_495_p1 = row_fu_176;

assign zext_ln555_fu_491_p1 = row_fu_176;

always @ (posedge ap_clk) begin
    zext_ln526_1_reg_791[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //fast_accel_xFfast7x7_0_3840_2160_0_1_2_2_1_2163_7_49_3
