# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/workspace/fastcorner/fastcorner.srcs/sources_1/bd/fastcorner_design/ip/fastcorner_design_fast_accel_0_0/fastcorner_design_fast_accel_0_0.xci
# IP: The module: 'fastcorner_design_fast_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/fastcorner/fastcorner.gen/sources_1/bd/fastcorner_design/ip/fastcorner_design_fast_accel_0_0/constraints/fast_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fastcorner_design_fast_accel_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/workspace/fastcorner/fastcorner.srcs/sources_1/bd/fastcorner_design/ip/fastcorner_design_fast_accel_0_0/fastcorner_design_fast_accel_0_0.xci
# IP: The module: 'fastcorner_design_fast_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/fastcorner/fastcorner.gen/sources_1/bd/fastcorner_design/ip/fastcorner_design_fast_accel_0_0/constraints/fast_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fastcorner_design_fast_accel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
