// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_xFCornerHarrisDetector (
        p_read,
        p_read1,
        grayin_mat_data_dout,
        grayin_mat_data_empty_n,
        grayin_mat_data_read,
        out_mat_data_din,
        out_mat_data_full_n,
        out_mat_data_write,
        img_height,
        img_width,
        p_threshold,
        k,
        ap_clk,
        ap_rst,
        img_height_ap_vld,
        img_width_ap_vld,
        p_threshold_ap_vld,
        k_ap_vld,
        ap_start,
        p_read_ap_vld,
        p_read1_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [15:0] p_read;
input  [15:0] p_read1;
input  [7:0] grayin_mat_data_dout;
input   grayin_mat_data_empty_n;
output   grayin_mat_data_read;
output  [7:0] out_mat_data_din;
input   out_mat_data_full_n;
output   out_mat_data_write;
input  [15:0] img_height;
input  [15:0] img_width;
input  [15:0] p_threshold;
input  [15:0] k;
input   ap_clk;
input   ap_rst;
input   img_height_ap_vld;
input   img_width_ap_vld;
input   p_threshold_ap_vld;
input   k_ap_vld;
input   ap_start;
input   p_read_ap_vld;
input   p_read1_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_start_full_n;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [15:0] entry_proc_U0_img_height_c32_din;
wire    entry_proc_U0_img_height_c32_write;
wire   [15:0] entry_proc_U0_img_height_c33_din;
wire    entry_proc_U0_img_height_c33_write;
wire   [15:0] entry_proc_U0_img_width_c39_din;
wire    entry_proc_U0_img_width_c39_write;
wire   [15:0] entry_proc_U0_img_width_c40_din;
wire    entry_proc_U0_img_width_c40_write;
wire   [15:0] entry_proc_U0_p_threshold_c_din;
wire    entry_proc_U0_p_threshold_c_write;
wire   [15:0] entry_proc_U0_k_c_din;
wire    entry_proc_U0_k_c_write;
wire    xFCornerHarrisDetector_Block_entry1_proc_U0_ap_start;
wire    xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done;
wire    xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue;
wire    xFCornerHarrisDetector_Block_entry1_proc_U0_ap_idle;
wire    xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_0;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_1;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_2;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_3;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_4;
wire   [15:0] xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_5;
wire    ap_channel_done_gradxy_cols_channel;
wire    gradxy_cols_channel_full_n;
reg    ap_sync_reg_channel_write_gradxy_cols_channel;
wire    ap_sync_channel_write_gradxy_cols_channel;
wire    ap_channel_done_gradxy_rows_channel;
wire    gradxy_rows_channel_full_n;
reg    ap_sync_reg_channel_write_gradxy_rows_channel;
wire    ap_sync_channel_write_gradxy_rows_channel;
wire    ap_channel_done_grady_2_cols_channel;
wire    grady_2_cols_channel_full_n;
reg    ap_sync_reg_channel_write_grady_2_cols_channel;
wire    ap_sync_channel_write_grady_2_cols_channel;
wire    ap_channel_done_grady_2_rows_channel;
wire    grady_2_rows_channel_full_n;
reg    ap_sync_reg_channel_write_grady_2_rows_channel;
wire    ap_sync_channel_write_grady_2_rows_channel;
wire    ap_channel_done_gradx_2_cols_channel;
wire    gradx_2_cols_channel_full_n;
reg    ap_sync_reg_channel_write_gradx_2_cols_channel;
wire    ap_sync_channel_write_gradx_2_cols_channel;
wire    ap_channel_done_gradx_2_rows_channel;
wire    gradx_2_rows_channel_full_n;
reg    ap_sync_reg_channel_write_gradx_2_rows_channel;
wire    ap_sync_channel_write_gradx_2_rows_channel;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_start;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_done;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_continue;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_idle;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grayin_mat_data_read;
wire   [15:0] Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_din;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_write;
wire   [15:0] Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_din;
wire    Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_start;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_full_n;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_done;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_continue;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_idle;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_ready;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_out;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx_mat_data_read;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_read;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_read;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_start;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_done;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_continue;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_idle;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_ready;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_start_out;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_start_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady_mat_data_read;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_write;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_read;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_read;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_write;
wire   [15:0] xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_din;
wire    xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_write;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_start;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_done;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_continue;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_idle;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_ready;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx1_mat_data_read;
wire   [15:0] xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_din;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_write;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_read;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_read;
wire   [15:0] xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_din;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_write;
wire   [15:0] xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_din;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_write;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_start;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_done;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_continue;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_idle;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_ready;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady1_mat_data_read;
wire   [15:0] xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_din;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_write;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_height_read;
wire    xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_width_read;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_start;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_done;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_continue;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_idle;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_ready;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradx2_mat_data_read;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_grady2_mat_data_read;
wire   [15:0] xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_din;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_write;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_height_read;
wire    xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_width_read;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_start;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_done;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_continue;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_idle;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_ready;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx_2_data_read;
wire   [15:0] boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_din;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_write;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_start;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_done;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_continue;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_idle;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_ready;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady_2_data_read;
wire   [15:0] boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_din;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_write;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_start;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_done;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_continue;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_idle;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_ready;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxy_data_read;
wire   [15:0] boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_din;
wire    boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_write;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_start;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_done;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_continue;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_idle;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_ready;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradx2g_data_read;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_grady2g_data_read;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradxyg_data_read;
wire   [31:0] xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_din;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_write;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_read;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_read;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_thresold_read;
wire   [15:0] xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_din;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_write;
wire   [15:0] xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_din;
wire    xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_write;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_start;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_done;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_continue;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_idle;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_ready;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_start_out;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_start_write;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_score_data_read;
wire   [31:0] xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_din;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_write;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_threshold_read;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_read;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_read;
wire   [15:0] xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_din;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_write;
wire   [15:0] xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_din;
wire    xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_write;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_start;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_done;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_continue;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_idle;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_ready;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_thresh_data_read;
wire   [7:0] xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_din;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_write;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_height_read;
wire    xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_width_read;
wire    img_height_c32_full_n;
wire   [15:0] img_height_c32_dout;
wire   [2:0] img_height_c32_num_data_valid;
wire   [2:0] img_height_c32_fifo_cap;
wire    img_height_c32_empty_n;
wire    img_height_c33_full_n;
wire   [15:0] img_height_c33_dout;
wire   [2:0] img_height_c33_num_data_valid;
wire   [2:0] img_height_c33_fifo_cap;
wire    img_height_c33_empty_n;
wire    img_width_c39_full_n;
wire   [15:0] img_width_c39_dout;
wire   [2:0] img_width_c39_num_data_valid;
wire   [2:0] img_width_c39_fifo_cap;
wire    img_width_c39_empty_n;
wire    img_width_c40_full_n;
wire   [15:0] img_width_c40_dout;
wire   [2:0] img_width_c40_num_data_valid;
wire   [2:0] img_width_c40_fifo_cap;
wire    img_width_c40_empty_n;
wire    p_threshold_c_full_n;
wire   [15:0] p_threshold_c_dout;
wire   [3:0] p_threshold_c_num_data_valid;
wire   [3:0] p_threshold_c_fifo_cap;
wire    p_threshold_c_empty_n;
wire    k_c_full_n;
wire   [15:0] k_c_dout;
wire   [3:0] k_c_num_data_valid;
wire   [3:0] k_c_fifo_cap;
wire    k_c_empty_n;
wire   [15:0] gradx_2_rows_channel_dout;
wire   [2:0] gradx_2_rows_channel_num_data_valid;
wire   [2:0] gradx_2_rows_channel_fifo_cap;
wire    gradx_2_rows_channel_empty_n;
wire   [15:0] gradx_2_cols_channel_dout;
wire   [2:0] gradx_2_cols_channel_num_data_valid;
wire   [2:0] gradx_2_cols_channel_fifo_cap;
wire    gradx_2_cols_channel_empty_n;
wire   [15:0] grady_2_rows_channel_dout;
wire   [2:0] grady_2_rows_channel_num_data_valid;
wire   [2:0] grady_2_rows_channel_fifo_cap;
wire    grady_2_rows_channel_empty_n;
wire   [15:0] grady_2_cols_channel_dout;
wire   [2:0] grady_2_cols_channel_num_data_valid;
wire   [2:0] grady_2_cols_channel_fifo_cap;
wire    grady_2_cols_channel_empty_n;
wire   [15:0] gradxy_rows_channel_dout;
wire   [2:0] gradxy_rows_channel_num_data_valid;
wire   [2:0] gradxy_rows_channel_fifo_cap;
wire    gradxy_rows_channel_empty_n;
wire   [15:0] gradxy_cols_channel_dout;
wire   [2:0] gradxy_cols_channel_num_data_valid;
wire   [2:0] gradxy_cols_channel_fifo_cap;
wire    gradxy_cols_channel_empty_n;
wire    gradx_mat_data_full_n;
wire   [15:0] gradx_mat_data_dout;
wire   [1:0] gradx_mat_data_num_data_valid;
wire   [1:0] gradx_mat_data_fifo_cap;
wire    gradx_mat_data_empty_n;
wire    grady_mat_data_full_n;
wire   [15:0] grady_mat_data_dout;
wire   [1:0] grady_mat_data_num_data_valid;
wire   [1:0] grady_mat_data_fifo_cap;
wire    grady_mat_data_empty_n;
wire    gradx1_mat_data_full_n;
wire   [15:0] gradx1_mat_data_dout;
wire   [1:0] gradx1_mat_data_num_data_valid;
wire   [1:0] gradx1_mat_data_fifo_cap;
wire    gradx1_mat_data_empty_n;
wire    gradx2_mat_data_full_n;
wire   [15:0] gradx2_mat_data_dout;
wire   [1:0] gradx2_mat_data_num_data_valid;
wire   [1:0] gradx2_mat_data_fifo_cap;
wire    gradx2_mat_data_empty_n;
wire    img_height_c29_full_n;
wire   [15:0] img_height_c29_dout;
wire   [1:0] img_height_c29_num_data_valid;
wire   [1:0] img_height_c29_fifo_cap;
wire    img_height_c29_empty_n;
wire    img_height_c31_full_n;
wire   [15:0] img_height_c31_dout;
wire   [1:0] img_height_c31_num_data_valid;
wire   [1:0] img_height_c31_fifo_cap;
wire    img_height_c31_empty_n;
wire    img_width_c36_full_n;
wire   [15:0] img_width_c36_dout;
wire   [1:0] img_width_c36_num_data_valid;
wire   [1:0] img_width_c36_fifo_cap;
wire    img_width_c36_empty_n;
wire    img_width_c38_full_n;
wire   [15:0] img_width_c38_dout;
wire   [1:0] img_width_c38_num_data_valid;
wire   [1:0] img_width_c38_fifo_cap;
wire    img_width_c38_empty_n;
wire    grady1_mat_data_full_n;
wire   [15:0] grady1_mat_data_dout;
wire   [1:0] grady1_mat_data_num_data_valid;
wire   [1:0] grady1_mat_data_fifo_cap;
wire    grady1_mat_data_empty_n;
wire    grady2_mat_data_full_n;
wire   [15:0] grady2_mat_data_dout;
wire   [1:0] grady2_mat_data_num_data_valid;
wire   [1:0] grady2_mat_data_fifo_cap;
wire    grady2_mat_data_empty_n;
wire    img_height_c30_full_n;
wire   [15:0] img_height_c30_dout;
wire   [1:0] img_height_c30_num_data_valid;
wire   [1:0] img_height_c30_fifo_cap;
wire    img_height_c30_empty_n;
wire    img_width_c37_full_n;
wire   [15:0] img_width_c37_dout;
wire   [1:0] img_width_c37_num_data_valid;
wire   [1:0] img_width_c37_fifo_cap;
wire    img_width_c37_empty_n;
wire    gradx_2_data_full_n;
wire   [15:0] gradx_2_data_dout;
wire   [1:0] gradx_2_data_num_data_valid;
wire   [1:0] gradx_2_data_fifo_cap;
wire    gradx_2_data_empty_n;
wire    img_height_c28_full_n;
wire   [15:0] img_height_c28_dout;
wire   [2:0] img_height_c28_num_data_valid;
wire   [2:0] img_height_c28_fifo_cap;
wire    img_height_c28_empty_n;
wire    img_width_c35_full_n;
wire   [15:0] img_width_c35_dout;
wire   [2:0] img_width_c35_num_data_valid;
wire   [2:0] img_width_c35_fifo_cap;
wire    img_width_c35_empty_n;
wire    grady_2_data_full_n;
wire   [15:0] grady_2_data_dout;
wire   [1:0] grady_2_data_num_data_valid;
wire   [1:0] grady_2_data_fifo_cap;
wire    grady_2_data_empty_n;
wire    gradxy_data_full_n;
wire   [15:0] gradxy_data_dout;
wire   [1:0] gradxy_data_num_data_valid;
wire   [1:0] gradxy_data_fifo_cap;
wire    gradxy_data_empty_n;
wire    gradx2g_data_full_n;
wire   [15:0] gradx2g_data_dout;
wire   [1:0] gradx2g_data_num_data_valid;
wire   [1:0] gradx2g_data_fifo_cap;
wire    gradx2g_data_empty_n;
wire    grady2g_data_full_n;
wire   [15:0] grady2g_data_dout;
wire   [1:0] grady2g_data_num_data_valid;
wire   [1:0] grady2g_data_fifo_cap;
wire    grady2g_data_empty_n;
wire    gradxyg_data_full_n;
wire   [15:0] gradxyg_data_dout;
wire   [1:0] gradxyg_data_num_data_valid;
wire   [1:0] gradxyg_data_fifo_cap;
wire    gradxyg_data_empty_n;
wire    score_data_full_n;
wire   [31:0] score_data_dout;
wire   [1:0] score_data_num_data_valid;
wire   [1:0] score_data_fifo_cap;
wire    score_data_empty_n;
wire    img_height_c27_full_n;
wire   [15:0] img_height_c27_dout;
wire   [1:0] img_height_c27_num_data_valid;
wire   [1:0] img_height_c27_fifo_cap;
wire    img_height_c27_empty_n;
wire    img_width_c34_full_n;
wire   [15:0] img_width_c34_dout;
wire   [1:0] img_width_c34_num_data_valid;
wire   [1:0] img_width_c34_fifo_cap;
wire    img_width_c34_empty_n;
wire    thresh_data_full_n;
wire   [31:0] thresh_data_dout;
wire   [1:0] thresh_data_num_data_valid;
wire   [1:0] thresh_data_fifo_cap;
wire    thresh_data_empty_n;
wire    img_height_c_full_n;
wire   [15:0] img_height_c_dout;
wire   [1:0] img_height_c_num_data_valid;
wire   [1:0] img_height_c_fifo_cap;
wire    img_height_c_empty_n;
wire    img_width_c_full_n;
wire   [15:0] img_width_c_dout;
wire   [1:0] img_width_c_num_data_valid;
wire   [1:0] img_width_c_fifo_cap;
wire    img_width_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready;
wire    ap_sync_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready;
reg    ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready;
wire    ap_sync_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready;
wire   [0:0] start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_din;
wire    start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_full_n;
wire   [0:0] start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_dout;
wire    start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_empty_n;
wire   [0:0] start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_din;
wire    start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_full_n;
wire   [0:0] start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_dout;
wire    start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_empty_n;
wire   [0:0] start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_din;
wire    start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_full_n;
wire   [0:0] start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_dout;
wire    start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_empty_n;
wire   [0:0] start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_din;
wire    start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_full_n;
wire   [0:0] start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_dout;
wire    start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_empty_n;
wire   [0:0] start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_din;
wire    start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_full_n;
wire   [0:0] start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_dout;
wire    start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_empty_n;
wire   [0:0] start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_din;
wire    start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_full_n;
wire   [0:0] start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_dout;
wire    start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_empty_n;
wire   [0:0] start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_din;
wire    start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_full_n;
wire   [0:0] start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_dout;
wire    start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_empty_n;
wire   [0:0] start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_din;
wire    start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_full_n;
wire   [0:0] start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_dout;
wire    start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_gradxy_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_gradxy_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_grady_2_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_grady_2_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_gradx_2_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_gradx_2_rows_channel = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready = 1'b0;
end

cornerHarris_accel_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(entry_proc_U0_start_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .img_height(img_height),
    .img_height_c32_din(entry_proc_U0_img_height_c32_din),
    .img_height_c32_num_data_valid(img_height_c32_num_data_valid),
    .img_height_c32_fifo_cap(img_height_c32_fifo_cap),
    .img_height_c32_full_n(img_height_c32_full_n),
    .img_height_c32_write(entry_proc_U0_img_height_c32_write),
    .img_height_c33_din(entry_proc_U0_img_height_c33_din),
    .img_height_c33_num_data_valid(img_height_c33_num_data_valid),
    .img_height_c33_fifo_cap(img_height_c33_fifo_cap),
    .img_height_c33_full_n(img_height_c33_full_n),
    .img_height_c33_write(entry_proc_U0_img_height_c33_write),
    .img_width(img_width),
    .img_width_c39_din(entry_proc_U0_img_width_c39_din),
    .img_width_c39_num_data_valid(img_width_c39_num_data_valid),
    .img_width_c39_fifo_cap(img_width_c39_fifo_cap),
    .img_width_c39_full_n(img_width_c39_full_n),
    .img_width_c39_write(entry_proc_U0_img_width_c39_write),
    .img_width_c40_din(entry_proc_U0_img_width_c40_din),
    .img_width_c40_num_data_valid(img_width_c40_num_data_valid),
    .img_width_c40_fifo_cap(img_width_c40_fifo_cap),
    .img_width_c40_full_n(img_width_c40_full_n),
    .img_width_c40_write(entry_proc_U0_img_width_c40_write),
    .p_threshold(p_threshold),
    .p_threshold_c_din(entry_proc_U0_p_threshold_c_din),
    .p_threshold_c_num_data_valid(p_threshold_c_num_data_valid),
    .p_threshold_c_fifo_cap(p_threshold_c_fifo_cap),
    .p_threshold_c_full_n(p_threshold_c_full_n),
    .p_threshold_c_write(entry_proc_U0_p_threshold_c_write),
    .k(k),
    .k_c_din(entry_proc_U0_k_c_din),
    .k_c_num_data_valid(k_c_num_data_valid),
    .k_c_fifo_cap(k_c_fifo_cap),
    .k_c_full_n(k_c_full_n),
    .k_c_write(entry_proc_U0_k_c_write)
);

cornerHarris_accel_xFCornerHarrisDetector_Block_entry1_proc xFCornerHarrisDetector_Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_start),
    .ap_done(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done),
    .ap_continue(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue),
    .ap_idle(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_idle),
    .ap_ready(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready),
    .img_height(img_height),
    .img_width(img_width),
    .ap_return_0(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_0),
    .ap_return_1(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_1),
    .ap_return_2(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_2),
    .ap_return_3(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_3),
    .ap_return_4(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_4),
    .ap_return_5(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_5)
);

cornerHarris_accel_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_s Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_start),
    .ap_done(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_done),
    .ap_continue(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_continue),
    .ap_idle(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_idle),
    .ap_ready(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .grayin_mat_data_dout(grayin_mat_data_dout),
    .grayin_mat_data_num_data_valid(2'd0),
    .grayin_mat_data_fifo_cap(2'd0),
    .grayin_mat_data_empty_n(grayin_mat_data_empty_n),
    .grayin_mat_data_read(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grayin_mat_data_read),
    .gradx_mat_data_din(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_din),
    .gradx_mat_data_num_data_valid(gradx_mat_data_num_data_valid),
    .gradx_mat_data_fifo_cap(gradx_mat_data_fifo_cap),
    .gradx_mat_data_full_n(gradx_mat_data_full_n),
    .gradx_mat_data_write(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_write),
    .grady_mat_data_din(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_din),
    .grady_mat_data_num_data_valid(grady_mat_data_num_data_valid),
    .grady_mat_data_fifo_cap(grady_mat_data_fifo_cap),
    .grady_mat_data_full_n(grady_mat_data_full_n),
    .grady_mat_data_write(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_write)
);

cornerHarris_accel_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1 xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_start),
    .start_full_n(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_full_n),
    .ap_done(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_done),
    .ap_continue(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_continue),
    .ap_idle(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_idle),
    .ap_ready(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_ready),
    .start_out(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_out),
    .start_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_write),
    .gradx_mat_data_dout(gradx_mat_data_dout),
    .gradx_mat_data_num_data_valid(gradx_mat_data_num_data_valid),
    .gradx_mat_data_fifo_cap(gradx_mat_data_fifo_cap),
    .gradx_mat_data_empty_n(gradx_mat_data_empty_n),
    .gradx_mat_data_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx_mat_data_read),
    .gradx1_mat_data_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_din),
    .gradx1_mat_data_num_data_valid(gradx1_mat_data_num_data_valid),
    .gradx1_mat_data_fifo_cap(gradx1_mat_data_fifo_cap),
    .gradx1_mat_data_full_n(gradx1_mat_data_full_n),
    .gradx1_mat_data_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_write),
    .gradx2_mat_data_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_din),
    .gradx2_mat_data_num_data_valid(gradx2_mat_data_num_data_valid),
    .gradx2_mat_data_fifo_cap(gradx2_mat_data_fifo_cap),
    .gradx2_mat_data_full_n(gradx2_mat_data_full_n),
    .gradx2_mat_data_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_write),
    .img_height_dout(img_height_c33_dout),
    .img_height_num_data_valid(img_height_c33_num_data_valid),
    .img_height_fifo_cap(img_height_c33_fifo_cap),
    .img_height_empty_n(img_height_c33_empty_n),
    .img_height_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_read),
    .img_width_dout(img_width_c40_dout),
    .img_width_num_data_valid(img_width_c40_num_data_valid),
    .img_width_fifo_cap(img_width_c40_fifo_cap),
    .img_width_empty_n(img_width_c40_empty_n),
    .img_width_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_read),
    .img_height_c29_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_din),
    .img_height_c29_num_data_valid(img_height_c29_num_data_valid),
    .img_height_c29_fifo_cap(img_height_c29_fifo_cap),
    .img_height_c29_full_n(img_height_c29_full_n),
    .img_height_c29_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_write),
    .img_height_c31_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_din),
    .img_height_c31_num_data_valid(img_height_c31_num_data_valid),
    .img_height_c31_fifo_cap(img_height_c31_fifo_cap),
    .img_height_c31_full_n(img_height_c31_full_n),
    .img_height_c31_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_write),
    .img_width_c36_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_din),
    .img_width_c36_num_data_valid(img_width_c36_num_data_valid),
    .img_width_c36_fifo_cap(img_width_c36_fifo_cap),
    .img_width_c36_full_n(img_width_c36_full_n),
    .img_width_c36_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_write),
    .img_width_c38_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_din),
    .img_width_c38_num_data_valid(img_width_c38_num_data_valid),
    .img_width_c38_fifo_cap(img_width_c38_fifo_cap),
    .img_width_c38_full_n(img_width_c38_full_n),
    .img_width_c38_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_write)
);

cornerHarris_accel_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_s xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_start),
    .start_full_n(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_full_n),
    .ap_done(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_done),
    .ap_continue(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_continue),
    .ap_idle(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_idle),
    .ap_ready(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_ready),
    .start_out(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_start_out),
    .start_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_start_write),
    .grady_mat_data_dout(grady_mat_data_dout),
    .grady_mat_data_num_data_valid(grady_mat_data_num_data_valid),
    .grady_mat_data_fifo_cap(grady_mat_data_fifo_cap),
    .grady_mat_data_empty_n(grady_mat_data_empty_n),
    .grady_mat_data_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady_mat_data_read),
    .grady1_mat_data_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_din),
    .grady1_mat_data_num_data_valid(grady1_mat_data_num_data_valid),
    .grady1_mat_data_fifo_cap(grady1_mat_data_fifo_cap),
    .grady1_mat_data_full_n(grady1_mat_data_full_n),
    .grady1_mat_data_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_write),
    .grady2_mat_data_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_din),
    .grady2_mat_data_num_data_valid(grady2_mat_data_num_data_valid),
    .grady2_mat_data_fifo_cap(grady2_mat_data_fifo_cap),
    .grady2_mat_data_full_n(grady2_mat_data_full_n),
    .grady2_mat_data_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_write),
    .img_height_dout(img_height_c32_dout),
    .img_height_num_data_valid(img_height_c32_num_data_valid),
    .img_height_fifo_cap(img_height_c32_fifo_cap),
    .img_height_empty_n(img_height_c32_empty_n),
    .img_height_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_read),
    .img_width_dout(img_width_c39_dout),
    .img_width_num_data_valid(img_width_c39_num_data_valid),
    .img_width_fifo_cap(img_width_c39_fifo_cap),
    .img_width_empty_n(img_width_c39_empty_n),
    .img_width_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_read),
    .img_height_c30_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_din),
    .img_height_c30_num_data_valid(img_height_c30_num_data_valid),
    .img_height_c30_fifo_cap(img_height_c30_fifo_cap),
    .img_height_c30_full_n(img_height_c30_full_n),
    .img_height_c30_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_write),
    .img_width_c37_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_din),
    .img_width_c37_num_data_valid(img_width_c37_num_data_valid),
    .img_width_c37_fifo_cap(img_width_c37_fifo_cap),
    .img_width_c37_full_n(img_width_c37_full_n),
    .img_width_c37_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_write)
);

cornerHarris_accel_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2 xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_start),
    .ap_done(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_done),
    .ap_continue(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_continue),
    .ap_idle(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_idle),
    .ap_ready(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_ready),
    .gradx1_mat_data_dout(gradx1_mat_data_dout),
    .gradx1_mat_data_num_data_valid(gradx1_mat_data_num_data_valid),
    .gradx1_mat_data_fifo_cap(gradx1_mat_data_fifo_cap),
    .gradx1_mat_data_empty_n(gradx1_mat_data_empty_n),
    .gradx1_mat_data_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx1_mat_data_read),
    .gradx_2_data_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_din),
    .gradx_2_data_num_data_valid(gradx_2_data_num_data_valid),
    .gradx_2_data_fifo_cap(gradx_2_data_fifo_cap),
    .gradx_2_data_full_n(gradx_2_data_full_n),
    .gradx_2_data_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_write),
    .img_height_dout(img_height_c31_dout),
    .img_height_num_data_valid(img_height_c31_num_data_valid),
    .img_height_fifo_cap(img_height_c31_fifo_cap),
    .img_height_empty_n(img_height_c31_empty_n),
    .img_height_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_read),
    .img_width_dout(img_width_c38_dout),
    .img_width_num_data_valid(img_width_c38_num_data_valid),
    .img_width_fifo_cap(img_width_c38_fifo_cap),
    .img_width_empty_n(img_width_c38_empty_n),
    .img_width_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_read),
    .img_height_c28_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_din),
    .img_height_c28_num_data_valid(img_height_c28_num_data_valid),
    .img_height_c28_fifo_cap(img_height_c28_fifo_cap),
    .img_height_c28_full_n(img_height_c28_full_n),
    .img_height_c28_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_write),
    .img_width_c35_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_din),
    .img_width_c35_num_data_valid(img_width_c35_num_data_valid),
    .img_width_c35_fifo_cap(img_width_c35_fifo_cap),
    .img_width_c35_full_n(img_width_c35_full_n),
    .img_width_c35_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_write)
);

cornerHarris_accel_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_s xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_start),
    .ap_done(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_done),
    .ap_continue(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_continue),
    .ap_idle(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_idle),
    .ap_ready(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_ready),
    .grady1_mat_data_dout(grady1_mat_data_dout),
    .grady1_mat_data_num_data_valid(grady1_mat_data_num_data_valid),
    .grady1_mat_data_fifo_cap(grady1_mat_data_fifo_cap),
    .grady1_mat_data_empty_n(grady1_mat_data_empty_n),
    .grady1_mat_data_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady1_mat_data_read),
    .grady_2_data_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_din),
    .grady_2_data_num_data_valid(grady_2_data_num_data_valid),
    .grady_2_data_fifo_cap(grady_2_data_fifo_cap),
    .grady_2_data_full_n(grady_2_data_full_n),
    .grady_2_data_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_write),
    .img_height_dout(img_height_c30_dout),
    .img_height_num_data_valid(img_height_c30_num_data_valid),
    .img_height_fifo_cap(img_height_c30_fifo_cap),
    .img_height_empty_n(img_height_c30_empty_n),
    .img_height_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_height_read),
    .img_width_dout(img_width_c37_dout),
    .img_width_num_data_valid(img_width_c37_num_data_valid),
    .img_width_fifo_cap(img_width_c37_fifo_cap),
    .img_width_empty_n(img_width_c37_empty_n),
    .img_width_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_width_read)
);

cornerHarris_accel_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_s xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_start),
    .ap_done(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_done),
    .ap_continue(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_continue),
    .ap_idle(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_idle),
    .ap_ready(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_ready),
    .gradx2_mat_data_dout(gradx2_mat_data_dout),
    .gradx2_mat_data_num_data_valid(gradx2_mat_data_num_data_valid),
    .gradx2_mat_data_fifo_cap(gradx2_mat_data_fifo_cap),
    .gradx2_mat_data_empty_n(gradx2_mat_data_empty_n),
    .gradx2_mat_data_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradx2_mat_data_read),
    .grady2_mat_data_dout(grady2_mat_data_dout),
    .grady2_mat_data_num_data_valid(grady2_mat_data_num_data_valid),
    .grady2_mat_data_fifo_cap(grady2_mat_data_fifo_cap),
    .grady2_mat_data_empty_n(grady2_mat_data_empty_n),
    .grady2_mat_data_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_grady2_mat_data_read),
    .gradxy_data_din(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_din),
    .gradxy_data_num_data_valid(gradxy_data_num_data_valid),
    .gradxy_data_fifo_cap(gradxy_data_fifo_cap),
    .gradxy_data_full_n(gradxy_data_full_n),
    .gradxy_data_write(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_write),
    .img_height_dout(img_height_c29_dout),
    .img_height_num_data_valid(img_height_c29_num_data_valid),
    .img_height_fifo_cap(img_height_c29_fifo_cap),
    .img_height_empty_n(img_height_c29_empty_n),
    .img_height_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_height_read),
    .img_width_dout(img_width_c36_dout),
    .img_width_num_data_valid(img_width_c36_num_data_valid),
    .img_width_fifo_cap(img_width_c36_fifo_cap),
    .img_width_empty_n(img_width_c36_empty_n),
    .img_width_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_width_read)
);

cornerHarris_accel_boxFilter_0_3_3_3840_2160_1_false_2_2_3 boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_start),
    .ap_done(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_done),
    .ap_continue(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_continue),
    .ap_idle(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_idle),
    .ap_ready(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_ready),
    .p_read(gradx_2_rows_channel_dout),
    .p_read1(gradx_2_cols_channel_dout),
    .gradx_2_data_dout(gradx_2_data_dout),
    .gradx_2_data_num_data_valid(gradx_2_data_num_data_valid),
    .gradx_2_data_fifo_cap(gradx_2_data_fifo_cap),
    .gradx_2_data_empty_n(gradx_2_data_empty_n),
    .gradx_2_data_read(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx_2_data_read),
    .gradx2g_data_din(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_din),
    .gradx2g_data_num_data_valid(gradx2g_data_num_data_valid),
    .gradx2g_data_fifo_cap(gradx2g_data_fifo_cap),
    .gradx2g_data_full_n(gradx2g_data_full_n),
    .gradx2g_data_write(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_write)
);

cornerHarris_accel_boxFilter_0_3_3_3840_2160_1_false_2_2_4 boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_start),
    .ap_done(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_done),
    .ap_continue(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_continue),
    .ap_idle(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_idle),
    .ap_ready(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_ready),
    .p_read(grady_2_rows_channel_dout),
    .p_read1(grady_2_cols_channel_dout),
    .grady_2_data_dout(grady_2_data_dout),
    .grady_2_data_num_data_valid(grady_2_data_num_data_valid),
    .grady_2_data_fifo_cap(grady_2_data_fifo_cap),
    .grady_2_data_empty_n(grady_2_data_empty_n),
    .grady_2_data_read(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady_2_data_read),
    .grady2g_data_din(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_din),
    .grady2g_data_num_data_valid(grady2g_data_num_data_valid),
    .grady2g_data_fifo_cap(grady2g_data_fifo_cap),
    .grady2g_data_full_n(grady2g_data_full_n),
    .grady2g_data_write(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_write)
);

cornerHarris_accel_boxFilter_0_3_3_3840_2160_1_false_2_2_s boxFilter_0_3_3_3840_2160_1_false_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_start),
    .ap_done(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_done),
    .ap_continue(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_continue),
    .ap_idle(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_idle),
    .ap_ready(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_ready),
    .p_read(gradxy_rows_channel_dout),
    .p_read1(gradxy_cols_channel_dout),
    .gradxy_data_dout(gradxy_data_dout),
    .gradxy_data_num_data_valid(gradxy_data_num_data_valid),
    .gradxy_data_fifo_cap(gradxy_data_fifo_cap),
    .gradxy_data_empty_n(gradxy_data_empty_n),
    .gradxy_data_read(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxy_data_read),
    .gradxyg_data_din(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_din),
    .gradxyg_data_num_data_valid(gradxyg_data_num_data_valid),
    .gradxyg_data_fifo_cap(gradxyg_data_fifo_cap),
    .gradxyg_data_full_n(gradxyg_data_full_n),
    .gradxyg_data_write(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_write)
);

cornerHarris_accel_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_s xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_start),
    .ap_done(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_done),
    .ap_continue(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_continue),
    .ap_idle(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_idle),
    .ap_ready(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_ready),
    .gradx2g_data_dout(gradx2g_data_dout),
    .gradx2g_data_num_data_valid(gradx2g_data_num_data_valid),
    .gradx2g_data_fifo_cap(gradx2g_data_fifo_cap),
    .gradx2g_data_empty_n(gradx2g_data_empty_n),
    .gradx2g_data_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradx2g_data_read),
    .grady2g_data_dout(grady2g_data_dout),
    .grady2g_data_num_data_valid(grady2g_data_num_data_valid),
    .grady2g_data_fifo_cap(grady2g_data_fifo_cap),
    .grady2g_data_empty_n(grady2g_data_empty_n),
    .grady2g_data_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_grady2g_data_read),
    .gradxyg_data_dout(gradxyg_data_dout),
    .gradxyg_data_num_data_valid(gradxyg_data_num_data_valid),
    .gradxyg_data_fifo_cap(gradxyg_data_fifo_cap),
    .gradxyg_data_empty_n(gradxyg_data_empty_n),
    .gradxyg_data_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradxyg_data_read),
    .score_data_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_din),
    .score_data_num_data_valid(score_data_num_data_valid),
    .score_data_fifo_cap(score_data_fifo_cap),
    .score_data_full_n(score_data_full_n),
    .score_data_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_write),
    .img_height_dout(img_height_c28_dout),
    .img_height_num_data_valid(img_height_c28_num_data_valid),
    .img_height_fifo_cap(img_height_c28_fifo_cap),
    .img_height_empty_n(img_height_c28_empty_n),
    .img_height_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_read),
    .img_width_dout(img_width_c35_dout),
    .img_width_num_data_valid(img_width_c35_num_data_valid),
    .img_width_fifo_cap(img_width_c35_fifo_cap),
    .img_width_empty_n(img_width_c35_empty_n),
    .img_width_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_read),
    .thresold_dout(k_c_dout),
    .thresold_num_data_valid(k_c_num_data_valid),
    .thresold_fifo_cap(k_c_fifo_cap),
    .thresold_empty_n(k_c_empty_n),
    .thresold_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_thresold_read),
    .img_height_c27_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_din),
    .img_height_c27_num_data_valid(img_height_c27_num_data_valid),
    .img_height_c27_fifo_cap(img_height_c27_fifo_cap),
    .img_height_c27_full_n(img_height_c27_full_n),
    .img_height_c27_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_write),
    .img_width_c34_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_din),
    .img_width_c34_num_data_valid(img_width_c34_num_data_valid),
    .img_width_c34_fifo_cap(img_width_c34_fifo_cap),
    .img_width_c34_full_n(img_width_c34_full_n),
    .img_width_c34_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_write)
);

cornerHarris_accel_xFThreshold_8_3840_2160_6_1_2_2_14_2160_s xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_start),
    .start_full_n(start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_full_n),
    .ap_done(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_done),
    .ap_continue(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_continue),
    .ap_idle(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_idle),
    .ap_ready(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_ready),
    .start_out(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_start_out),
    .start_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_start_write),
    .score_data_dout(score_data_dout),
    .score_data_num_data_valid(score_data_num_data_valid),
    .score_data_fifo_cap(score_data_fifo_cap),
    .score_data_empty_n(score_data_empty_n),
    .score_data_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_score_data_read),
    .thresh_data_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_din),
    .thresh_data_num_data_valid(thresh_data_num_data_valid),
    .thresh_data_fifo_cap(thresh_data_fifo_cap),
    .thresh_data_full_n(thresh_data_full_n),
    .thresh_data_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_write),
    .threshold_dout(p_threshold_c_dout),
    .threshold_num_data_valid(p_threshold_c_num_data_valid),
    .threshold_fifo_cap(p_threshold_c_fifo_cap),
    .threshold_empty_n(p_threshold_c_empty_n),
    .threshold_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_threshold_read),
    .img_height_dout(img_height_c27_dout),
    .img_height_num_data_valid(img_height_c27_num_data_valid),
    .img_height_fifo_cap(img_height_c27_fifo_cap),
    .img_height_empty_n(img_height_c27_empty_n),
    .img_height_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_read),
    .img_width_dout(img_width_c34_dout),
    .img_width_num_data_valid(img_width_c34_num_data_valid),
    .img_width_fifo_cap(img_width_c34_fifo_cap),
    .img_width_empty_n(img_width_c34_empty_n),
    .img_width_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_read),
    .img_height_c_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_din),
    .img_height_c_num_data_valid(img_height_c_num_data_valid),
    .img_height_c_fifo_cap(img_height_c_fifo_cap),
    .img_height_c_full_n(img_height_c_full_n),
    .img_height_c_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_write),
    .img_width_c_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_din),
    .img_width_c_num_data_valid(img_width_c_num_data_valid),
    .img_width_c_fifo_cap(img_width_c_fifo_cap),
    .img_width_c_full_n(img_width_c_full_n),
    .img_width_c_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_write)
);

cornerHarris_accel_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_s xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_start),
    .ap_done(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_done),
    .ap_continue(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_continue),
    .ap_idle(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_idle),
    .ap_ready(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_ready),
    .thresh_data_dout(thresh_data_dout),
    .thresh_data_num_data_valid(thresh_data_num_data_valid),
    .thresh_data_fifo_cap(thresh_data_fifo_cap),
    .thresh_data_empty_n(thresh_data_empty_n),
    .thresh_data_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_thresh_data_read),
    .out_mat_data_din(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_din),
    .out_mat_data_num_data_valid(2'd0),
    .out_mat_data_fifo_cap(2'd0),
    .out_mat_data_full_n(out_mat_data_full_n),
    .out_mat_data_write(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_write),
    .img_height_dout(img_height_c_dout),
    .img_height_num_data_valid(img_height_c_num_data_valid),
    .img_height_fifo_cap(img_height_c_fifo_cap),
    .img_height_empty_n(img_height_c_empty_n),
    .img_height_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_height_read),
    .img_width_dout(img_width_c_dout),
    .img_width_num_data_valid(img_width_c_num_data_valid),
    .img_width_fifo_cap(img_width_c_fifo_cap),
    .img_width_empty_n(img_width_c_empty_n),
    .img_width_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d3_S img_height_c32_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_img_height_c32_din),
    .if_full_n(img_height_c32_full_n),
    .if_write(entry_proc_U0_img_height_c32_write),
    .if_dout(img_height_c32_dout),
    .if_num_data_valid(img_height_c32_num_data_valid),
    .if_fifo_cap(img_height_c32_fifo_cap),
    .if_empty_n(img_height_c32_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d3_S img_height_c33_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_img_height_c33_din),
    .if_full_n(img_height_c33_full_n),
    .if_write(entry_proc_U0_img_height_c33_write),
    .if_dout(img_height_c33_dout),
    .if_num_data_valid(img_height_c33_num_data_valid),
    .if_fifo_cap(img_height_c33_fifo_cap),
    .if_empty_n(img_height_c33_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d3_S img_width_c39_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_img_width_c39_din),
    .if_full_n(img_width_c39_full_n),
    .if_write(entry_proc_U0_img_width_c39_write),
    .if_dout(img_width_c39_dout),
    .if_num_data_valid(img_width_c39_num_data_valid),
    .if_fifo_cap(img_width_c39_fifo_cap),
    .if_empty_n(img_width_c39_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d3_S img_width_c40_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_img_width_c40_din),
    .if_full_n(img_width_c40_full_n),
    .if_write(entry_proc_U0_img_width_c40_write),
    .if_dout(img_width_c40_dout),
    .if_num_data_valid(img_width_c40_num_data_valid),
    .if_fifo_cap(img_width_c40_fifo_cap),
    .if_empty_n(img_width_c40_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d7_S p_threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_p_threshold_c_din),
    .if_full_n(p_threshold_c_full_n),
    .if_write(entry_proc_U0_p_threshold_c_write),
    .if_dout(p_threshold_c_dout),
    .if_num_data_valid(p_threshold_c_num_data_valid),
    .if_fifo_cap(p_threshold_c_fifo_cap),
    .if_empty_n(p_threshold_c_empty_n),
    .if_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_threshold_read)
);

cornerHarris_accel_fifo_w16_d6_S k_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_k_c_din),
    .if_full_n(k_c_full_n),
    .if_write(entry_proc_U0_k_c_write),
    .if_dout(k_c_dout),
    .if_num_data_valid(k_c_num_data_valid),
    .if_fifo_cap(k_c_fifo_cap),
    .if_empty_n(k_c_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_thresold_read)
);

cornerHarris_accel_fifo_w16_d4_S gradx_2_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_0),
    .if_full_n(gradx_2_rows_channel_full_n),
    .if_write(ap_channel_done_gradx_2_rows_channel),
    .if_dout(gradx_2_rows_channel_dout),
    .if_num_data_valid(gradx_2_rows_channel_num_data_valid),
    .if_fifo_cap(gradx_2_rows_channel_fifo_cap),
    .if_empty_n(gradx_2_rows_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d4_S gradx_2_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_1),
    .if_full_n(gradx_2_cols_channel_full_n),
    .if_write(ap_channel_done_gradx_2_cols_channel),
    .if_dout(gradx_2_cols_channel_dout),
    .if_num_data_valid(gradx_2_cols_channel_num_data_valid),
    .if_fifo_cap(gradx_2_cols_channel_fifo_cap),
    .if_empty_n(gradx_2_cols_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d4_S grady_2_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_2),
    .if_full_n(grady_2_rows_channel_full_n),
    .if_write(ap_channel_done_grady_2_rows_channel),
    .if_dout(grady_2_rows_channel_dout),
    .if_num_data_valid(grady_2_rows_channel_num_data_valid),
    .if_fifo_cap(grady_2_rows_channel_fifo_cap),
    .if_empty_n(grady_2_rows_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d4_S grady_2_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_3),
    .if_full_n(grady_2_cols_channel_full_n),
    .if_write(ap_channel_done_grady_2_cols_channel),
    .if_dout(grady_2_cols_channel_dout),
    .if_num_data_valid(grady_2_cols_channel_num_data_valid),
    .if_fifo_cap(grady_2_cols_channel_fifo_cap),
    .if_empty_n(grady_2_cols_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d4_S gradxy_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_4),
    .if_full_n(gradxy_rows_channel_full_n),
    .if_write(ap_channel_done_gradxy_rows_channel),
    .if_dout(gradxy_rows_channel_dout),
    .if_num_data_valid(gradxy_rows_channel_num_data_valid),
    .if_fifo_cap(gradxy_rows_channel_fifo_cap),
    .if_empty_n(gradxy_rows_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d4_S gradxy_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_Block_entry1_proc_U0_ap_return_5),
    .if_full_n(gradxy_cols_channel_full_n),
    .if_write(ap_channel_done_gradxy_cols_channel),
    .if_dout(gradxy_cols_channel_dout),
    .if_num_data_valid(gradxy_cols_channel_num_data_valid),
    .if_fifo_cap(gradxy_cols_channel_fifo_cap),
    .if_empty_n(gradxy_cols_channel_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_ready)
);

cornerHarris_accel_fifo_w16_d2_S gradx_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_din),
    .if_full_n(gradx_mat_data_full_n),
    .if_write(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_gradx_mat_data_write),
    .if_dout(gradx_mat_data_dout),
    .if_num_data_valid(gradx_mat_data_num_data_valid),
    .if_fifo_cap(gradx_mat_data_fifo_cap),
    .if_empty_n(gradx_mat_data_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S grady_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_din),
    .if_full_n(grady_mat_data_full_n),
    .if_write(Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grady_mat_data_write),
    .if_dout(grady_mat_data_dout),
    .if_num_data_valid(grady_mat_data_num_data_valid),
    .if_fifo_cap(grady_mat_data_fifo_cap),
    .if_empty_n(grady_mat_data_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S gradx1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_din),
    .if_full_n(gradx1_mat_data_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx1_mat_data_write),
    .if_dout(gradx1_mat_data_dout),
    .if_num_data_valid(gradx1_mat_data_num_data_valid),
    .if_fifo_cap(gradx1_mat_data_fifo_cap),
    .if_empty_n(gradx1_mat_data_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx1_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S gradx2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_din),
    .if_full_n(gradx2_mat_data_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_gradx2_mat_data_write),
    .if_dout(gradx2_mat_data_dout),
    .if_num_data_valid(gradx2_mat_data_num_data_valid),
    .if_fifo_cap(gradx2_mat_data_fifo_cap),
    .if_empty_n(gradx2_mat_data_empty_n),
    .if_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradx2_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S img_height_c29_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_din),
    .if_full_n(img_height_c29_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c29_write),
    .if_dout(img_height_c29_dout),
    .if_num_data_valid(img_height_c29_num_data_valid),
    .if_fifo_cap(img_height_c29_fifo_cap),
    .if_empty_n(img_height_c29_empty_n),
    .if_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d2_S img_height_c31_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_din),
    .if_full_n(img_height_c31_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_height_c31_write),
    .if_dout(img_height_c31_dout),
    .if_num_data_valid(img_height_c31_num_data_valid),
    .if_fifo_cap(img_height_c31_fifo_cap),
    .if_empty_n(img_height_c31_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d2_S img_width_c36_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_din),
    .if_full_n(img_width_c36_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c36_write),
    .if_dout(img_width_c36_dout),
    .if_num_data_valid(img_width_c36_num_data_valid),
    .if_fifo_cap(img_width_c36_fifo_cap),
    .if_empty_n(img_width_c36_empty_n),
    .if_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d2_S img_width_c38_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_din),
    .if_full_n(img_width_c38_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_img_width_c38_write),
    .if_dout(img_width_c38_dout),
    .if_num_data_valid(img_width_c38_num_data_valid),
    .if_fifo_cap(img_width_c38_fifo_cap),
    .if_empty_n(img_width_c38_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d2_S grady1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_din),
    .if_full_n(grady1_mat_data_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady1_mat_data_write),
    .if_dout(grady1_mat_data_dout),
    .if_num_data_valid(grady1_mat_data_num_data_valid),
    .if_fifo_cap(grady1_mat_data_fifo_cap),
    .if_empty_n(grady1_mat_data_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady1_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S grady2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_din),
    .if_full_n(grady2_mat_data_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_grady2_mat_data_write),
    .if_dout(grady2_mat_data_dout),
    .if_num_data_valid(grady2_mat_data_num_data_valid),
    .if_fifo_cap(grady2_mat_data_fifo_cap),
    .if_empty_n(grady2_mat_data_empty_n),
    .if_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_grady2_mat_data_read)
);

cornerHarris_accel_fifo_w16_d2_S img_height_c30_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_din),
    .if_full_n(img_height_c30_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_height_c30_write),
    .if_dout(img_height_c30_dout),
    .if_num_data_valid(img_height_c30_num_data_valid),
    .if_fifo_cap(img_height_c30_fifo_cap),
    .if_empty_n(img_height_c30_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d2_S img_width_c37_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_din),
    .if_full_n(img_width_c37_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_img_width_c37_write),
    .if_dout(img_width_c37_dout),
    .if_num_data_valid(img_width_c37_num_data_valid),
    .if_fifo_cap(img_width_c37_fifo_cap),
    .if_empty_n(img_width_c37_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d2_S gradx_2_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_din),
    .if_full_n(gradx_2_data_full_n),
    .if_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_gradx_2_data_write),
    .if_dout(gradx_2_data_dout),
    .if_num_data_valid(gradx_2_data_num_data_valid),
    .if_fifo_cap(gradx_2_data_fifo_cap),
    .if_empty_n(gradx_2_data_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx_2_data_read)
);

cornerHarris_accel_fifo_w16_d3_S img_height_c28_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_din),
    .if_full_n(img_height_c28_full_n),
    .if_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_height_c28_write),
    .if_dout(img_height_c28_dout),
    .if_num_data_valid(img_height_c28_num_data_valid),
    .if_fifo_cap(img_height_c28_fifo_cap),
    .if_empty_n(img_height_c28_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d3_S img_width_c35_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_din),
    .if_full_n(img_width_c35_full_n),
    .if_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_img_width_c35_write),
    .if_dout(img_width_c35_dout),
    .if_num_data_valid(img_width_c35_num_data_valid),
    .if_fifo_cap(img_width_c35_fifo_cap),
    .if_empty_n(img_width_c35_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_read)
);

cornerHarris_accel_fifo_w16_d2_S grady_2_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_din),
    .if_full_n(grady_2_data_full_n),
    .if_write(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_grady_2_data_write),
    .if_dout(grady_2_data_dout),
    .if_num_data_valid(grady_2_data_num_data_valid),
    .if_fifo_cap(grady_2_data_fifo_cap),
    .if_empty_n(grady_2_data_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady_2_data_read)
);

cornerHarris_accel_fifo_w16_d2_S gradxy_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_din),
    .if_full_n(gradxy_data_full_n),
    .if_write(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_gradxy_data_write),
    .if_dout(gradxy_data_dout),
    .if_num_data_valid(gradxy_data_num_data_valid),
    .if_fifo_cap(gradxy_data_fifo_cap),
    .if_empty_n(gradxy_data_empty_n),
    .if_read(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxy_data_read)
);

cornerHarris_accel_fifo_w16_d2_S gradx2g_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_din),
    .if_full_n(gradx2g_data_full_n),
    .if_write(boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_gradx2g_data_write),
    .if_dout(gradx2g_data_dout),
    .if_num_data_valid(gradx2g_data_num_data_valid),
    .if_fifo_cap(gradx2g_data_fifo_cap),
    .if_empty_n(gradx2g_data_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradx2g_data_read)
);

cornerHarris_accel_fifo_w16_d2_S grady2g_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_din),
    .if_full_n(grady2g_data_full_n),
    .if_write(boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_grady2g_data_write),
    .if_dout(grady2g_data_dout),
    .if_num_data_valid(grady2g_data_num_data_valid),
    .if_fifo_cap(grady2g_data_fifo_cap),
    .if_empty_n(grady2g_data_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_grady2g_data_read)
);

cornerHarris_accel_fifo_w16_d2_S gradxyg_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_din),
    .if_full_n(gradxyg_data_full_n),
    .if_write(boxFilter_0_3_3_3840_2160_1_false_2_2_U0_gradxyg_data_write),
    .if_dout(gradxyg_data_dout),
    .if_num_data_valid(gradxyg_data_num_data_valid),
    .if_fifo_cap(gradxyg_data_fifo_cap),
    .if_empty_n(gradxyg_data_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_gradxyg_data_read)
);

cornerHarris_accel_fifo_w32_d2_S score_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_din),
    .if_full_n(score_data_full_n),
    .if_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_score_data_write),
    .if_dout(score_data_dout),
    .if_num_data_valid(score_data_num_data_valid),
    .if_fifo_cap(score_data_fifo_cap),
    .if_empty_n(score_data_empty_n),
    .if_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_score_data_read)
);

cornerHarris_accel_fifo_w16_d2_S img_height_c27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_din),
    .if_full_n(img_height_c27_full_n),
    .if_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_height_c27_write),
    .if_dout(img_height_c27_dout),
    .if_num_data_valid(img_height_c27_num_data_valid),
    .if_fifo_cap(img_height_c27_fifo_cap),
    .if_empty_n(img_height_c27_empty_n),
    .if_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d2_S img_width_c34_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_din),
    .if_full_n(img_width_c34_full_n),
    .if_write(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_img_width_c34_write),
    .if_dout(img_width_c34_dout),
    .if_num_data_valid(img_width_c34_num_data_valid),
    .if_fifo_cap(img_width_c34_fifo_cap),
    .if_empty_n(img_width_c34_empty_n),
    .if_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_read)
);

cornerHarris_accel_fifo_w32_d2_S thresh_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_din),
    .if_full_n(thresh_data_full_n),
    .if_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_thresh_data_write),
    .if_dout(thresh_data_dout),
    .if_num_data_valid(thresh_data_num_data_valid),
    .if_fifo_cap(thresh_data_fifo_cap),
    .if_empty_n(thresh_data_empty_n),
    .if_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_thresh_data_read)
);

cornerHarris_accel_fifo_w16_d2_S img_height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_din),
    .if_full_n(img_height_c_full_n),
    .if_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_height_c_write),
    .if_dout(img_height_c_dout),
    .if_num_data_valid(img_height_c_num_data_valid),
    .if_fifo_cap(img_height_c_fifo_cap),
    .if_empty_n(img_height_c_empty_n),
    .if_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_height_read)
);

cornerHarris_accel_fifo_w16_d2_S img_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_din),
    .if_full_n(img_width_c_full_n),
    .if_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_img_width_c_write),
    .if_dout(img_width_c_dout),
    .if_num_data_valid(img_width_c_num_data_valid),
    .if_fifo_cap(img_width_c_fifo_cap),
    .if_empty_n(img_width_c_empty_n),
    .if_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_img_width_read)
);

cornerHarris_accel_start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0 start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_din),
    .if_full_n(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_dout),
    .if_empty_n(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_ready)
);

cornerHarris_accel_start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0 start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_din),
    .if_full_n(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_dout),
    .if_empty_n(start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_empty_n),
    .if_read(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_ready)
);

cornerHarris_accel_start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0 start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_din),
    .if_full_n(start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_dout),
    .if_empty_n(start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_empty_n),
    .if_read(xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_ready)
);

cornerHarris_accel_start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0 start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_din),
    .if_full_n(start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_dout),
    .if_empty_n(start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_empty_n),
    .if_read(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_ready)
);

cornerHarris_accel_start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0 start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_din),
    .if_full_n(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_write),
    .if_dout(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_dout),
    .if_empty_n(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_ready)
);

cornerHarris_accel_start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0 start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_din),
    .if_full_n(start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_write),
    .if_dout(start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_dout),
    .if_empty_n(start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_empty_n),
    .if_read(xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_ready)
);

cornerHarris_accel_start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0 start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_din),
    .if_full_n(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_full_n),
    .if_write(xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_start_write),
    .if_dout(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_dout),
    .if_empty_n(start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_empty_n),
    .if_read(xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_ready)
);

cornerHarris_accel_start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0 start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_din),
    .if_full_n(start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_full_n),
    .if_write(xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_start_write),
    .if_dout(start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_dout),
    .if_empty_n(start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_empty_n),
    .if_read(xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready <= ap_sync_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_gradx_2_cols_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_gradx_2_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_gradx_2_cols_channel <= ap_sync_channel_write_gradx_2_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_gradx_2_rows_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_gradx_2_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_gradx_2_rows_channel <= ap_sync_channel_write_gradx_2_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_gradxy_cols_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_gradxy_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_gradxy_cols_channel <= ap_sync_channel_write_gradxy_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_gradxy_rows_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_gradxy_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_gradxy_rows_channel <= ap_sync_channel_write_gradxy_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_grady_2_cols_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_grady_2_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_grady_2_cols_channel <= ap_sync_channel_write_grady_2_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_grady_2_rows_channel <= 1'b0;
    end else begin
        if (((xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_grady_2_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_grady_2_rows_channel <= ap_sync_channel_write_grady_2_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready <= ap_sync_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready;
        end
    end
end

assign Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_continue = 1'b1;

assign Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_start = ((ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_channel_done_gradx_2_cols_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_gradx_2_cols_channel ^ 1'b1));

assign ap_channel_done_gradx_2_rows_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_gradx_2_rows_channel ^ 1'b1));

assign ap_channel_done_gradxy_cols_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_gradxy_cols_channel ^ 1'b1));

assign ap_channel_done_gradxy_rows_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_gradxy_rows_channel ^ 1'b1));

assign ap_channel_done_grady_2_cols_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_grady_2_cols_channel ^ 1'b1));

assign ap_channel_done_grady_2_rows_channel = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_done & (ap_sync_reg_channel_write_grady_2_rows_channel ^ 1'b1));

assign ap_done = xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_done;

assign ap_idle = (xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_idle & xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_idle & xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_idle & xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_idle & xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_idle & xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_idle & xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_idle & xFCornerHarrisDetector_Block_entry1_proc_U0_ap_idle & xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_idle & (gradxy_cols_channel_empty_n ^ 1'b1) & (gradxy_rows_channel_empty_n ^ 1'b1) & (grady_2_cols_channel_empty_n ^ 1'b1) & (grady_2_rows_channel_empty_n ^ 1'b1) & (gradx_2_cols_channel_empty_n ^ 1'b1) & (gradx_2_rows_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_idle & boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_idle & boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_idle & Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready = (ap_sync_reg_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready | Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready);

assign ap_sync_channel_write_gradx_2_cols_channel = ((gradx_2_cols_channel_full_n & ap_channel_done_gradx_2_cols_channel) | ap_sync_reg_channel_write_gradx_2_cols_channel);

assign ap_sync_channel_write_gradx_2_rows_channel = ((gradx_2_rows_channel_full_n & ap_channel_done_gradx_2_rows_channel) | ap_sync_reg_channel_write_gradx_2_rows_channel);

assign ap_sync_channel_write_gradxy_cols_channel = ((gradxy_cols_channel_full_n & ap_channel_done_gradxy_cols_channel) | ap_sync_reg_channel_write_gradxy_cols_channel);

assign ap_sync_channel_write_gradxy_rows_channel = ((gradxy_rows_channel_full_n & ap_channel_done_gradxy_rows_channel) | ap_sync_reg_channel_write_gradxy_rows_channel);

assign ap_sync_channel_write_grady_2_cols_channel = ((grady_2_cols_channel_full_n & ap_channel_done_grady_2_cols_channel) | ap_sync_reg_channel_write_grady_2_cols_channel);

assign ap_sync_channel_write_grady_2_rows_channel = ((grady_2_rows_channel_full_n & ap_channel_done_grady_2_rows_channel) | ap_sync_reg_channel_write_grady_2_rows_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready & ap_sync_Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_ap_ready);

assign ap_sync_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready = (xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready | ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready);

assign boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_continue = 1'b1;

assign boxFilter_0_3_3_3840_2160_1_false_2_2_3_U0_ap_start = (gradx_2_rows_channel_empty_n & gradx_2_cols_channel_empty_n);

assign boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_continue = 1'b1;

assign boxFilter_0_3_3_3840_2160_1_false_2_2_4_U0_ap_start = (grady_2_rows_channel_empty_n & grady_2_cols_channel_empty_n);

assign boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_continue = 1'b1;

assign boxFilter_0_3_3_3840_2160_1_false_2_2_U0_ap_start = (gradxy_rows_channel_empty_n & gradxy_cols_channel_empty_n);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_start_full_n = (start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_full_n & start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_full_n & start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_full_n & start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_full_n);

assign grayin_mat_data_read = Sobel_0_3_0_3_3840_2160_1_false_2_2_2_U0_grayin_mat_data_read;

assign out_mat_data_din = xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_din;

assign out_mat_data_write = xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_out_mat_data_write;

assign start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_din = 1'b1;

assign start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_din = 1'b1;

assign start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_din = 1'b1;

assign start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_din = 1'b1;

assign start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_din = 1'b1;

assign start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_din = 1'b1;

assign start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_din = 1'b1;

assign start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_din = 1'b1;

assign xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_continue = 1'b1;

assign xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_ap_start = start_for_xFComputeScore_3_8_3840_2160_4_6_1_2_2_2_2_6_14_2160_U0_empty_n;

assign xFCornerHarrisDetector_Block_entry1_proc_U0_ap_continue = (ap_sync_channel_write_grady_2_rows_channel & ap_sync_channel_write_grady_2_cols_channel & ap_sync_channel_write_gradxy_rows_channel & ap_sync_channel_write_gradxy_cols_channel & ap_sync_channel_write_gradx_2_rows_channel & ap_sync_channel_write_gradx_2_cols_channel);

assign xFCornerHarrisDetector_Block_entry1_proc_U0_ap_start = ((ap_sync_reg_xFCornerHarrisDetector_Block_entry1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_continue = 1'b1;

assign xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_ap_start = start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_empty_n;

assign xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_1_U0_start_full_n = (start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_full_n & start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_full_n);

assign xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_continue = 1'b1;

assign xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_ap_start = start_for_xFDuplicate_3_3840_2160_4_1_2_2_2_6_2160_U0_empty_n;

assign xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_continue = ap_continue;

assign xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_ap_start = start_for_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_U0_empty_n;

assign xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_continue = 1'b1;

assign xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_ap_start = start_for_xFMultiply_3_3_3840_2160_4_4_1_2_2_2_6_6_2160_int_U0_empty_n;

assign xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_continue = 1'b1;

assign xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_ap_start = start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_2_U0_empty_n;

assign xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_continue = 1'b1;

assign xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_ap_start = start_for_xFSquare_3_3_3840_2160_4_4_1_2_2_6_6_2160_int_U0_empty_n;

assign xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_continue = 1'b1;

assign xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_ap_start = start_for_xFThreshold_8_3840_2160_6_1_2_2_14_2160_U0_empty_n;

endmodule //cornerHarris_accel_xFCornerHarrisDetector
