// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_xFSuppressionRad2_1_6_ap_uint_8_s (
        ap_ready,
        l00_buf_2_val,
        l10_buf_1_val,
        l10_buf_2_val,
        l10_buf_3_val,
        l20_buf_0_val,
        l20_buf_1_val,
        l20_buf_2_val,
        l20_buf_3_val,
        l20_buf_4_val,
        l30_buf_1_val,
        l30_buf_2_val,
        l30_buf_3_val,
        l40_buf_2_val,
        ap_return
);


output   ap_ready;
input  [31:0] l00_buf_2_val;
input  [31:0] l10_buf_1_val;
input  [31:0] l10_buf_2_val;
input  [31:0] l10_buf_3_val;
input  [31:0] l20_buf_0_val;
input  [31:0] l20_buf_1_val;
input  [31:0] l20_buf_2_val;
input  [31:0] l20_buf_3_val;
input  [31:0] l20_buf_4_val;
input  [31:0] l30_buf_1_val;
input  [31:0] l30_buf_2_val;
input  [31:0] l30_buf_3_val;
input  [31:0] l40_buf_2_val;
output  [0:0] ap_return;

wire    Max_xFFindMaxRad2_ap_int_32_s_fu_108_ap_ready;
wire   [0:0] Max_xFFindMaxRad2_ap_int_32_s_fu_108_ap_return;

cornerHarris_accel_xFFindMaxRad2_ap_int_32_s Max_xFFindMaxRad2_ap_int_32_s_fu_108(
    .ap_ready(Max_xFFindMaxRad2_ap_int_32_s_fu_108_ap_ready),
    .l22_val(l20_buf_2_val),
    .l02_val(l00_buf_2_val),
    .l11_val(l10_buf_1_val),
    .l12_val(l10_buf_2_val),
    .l13_val(l10_buf_3_val),
    .l20_val(l20_buf_0_val),
    .l21_val(l20_buf_1_val),
    .l23_val(l20_buf_3_val),
    .l24_val(l20_buf_4_val),
    .l31_val(l30_buf_1_val),
    .l32_val(l30_buf_2_val),
    .l33_val(l30_buf_3_val),
    .l42_val(l40_buf_2_val),
    .ap_return(Max_xFFindMaxRad2_ap_int_32_s_fu_108_ap_return)
);

assign ap_ready = 1'b1;

assign ap_return = Max_xFFindMaxRad2_ap_int_32_s_fu_108_ap_return;

endmodule //cornerHarris_accel_xFSuppressionRad2_1_6_ap_uint_8_s
