// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        thresh_data_dout,
        thresh_data_num_data_valid,
        thresh_data_fifo_cap,
        thresh_data_empty_n,
        thresh_data_read,
        out_mat_data_din,
        out_mat_data_num_data_valid,
        out_mat_data_fifo_cap,
        out_mat_data_full_n,
        out_mat_data_write,
        img_height_dout,
        img_height_num_data_valid,
        img_height_fifo_cap,
        img_height_empty_n,
        img_height_read,
        img_width_dout,
        img_width_num_data_valid,
        img_width_fifo_cap,
        img_width_empty_n,
        img_width_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] thresh_data_dout;
input  [1:0] thresh_data_num_data_valid;
input  [1:0] thresh_data_fifo_cap;
input   thresh_data_empty_n;
output   thresh_data_read;
output  [7:0] out_mat_data_din;
input  [1:0] out_mat_data_num_data_valid;
input  [1:0] out_mat_data_fifo_cap;
input   out_mat_data_full_n;
output   out_mat_data_write;
input  [15:0] img_height_dout;
input  [1:0] img_height_num_data_valid;
input  [1:0] img_height_fifo_cap;
input   img_height_empty_n;
output   img_height_read;
input  [15:0] img_width_dout;
input  [1:0] img_width_num_data_valid;
input  [1:0] img_width_fifo_cap;
input   img_width_empty_n;
output   img_width_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg thresh_data_read;
reg out_mat_data_write;
reg img_height_read;
reg img_width_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_height_blk_n;
reg    img_width_blk_n;
reg   [15:0] img_width_read_reg_56;
reg    ap_block_state1;
reg   [15:0] img_height_read_reg_61;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_idle;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_ready;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_thresh_data_read;
wire   [7:0] grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_din;
wire    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_write;
reg    grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg;
reg    ap_block_state1_ignore_call6;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg = 1'b0;
end

cornerHarris_accel_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start),
    .ap_done(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done),
    .ap_idle(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_idle),
    .ap_ready(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_ready),
    .thresh_data_dout(thresh_data_dout),
    .thresh_data_num_data_valid(2'd0),
    .thresh_data_fifo_cap(2'd0),
    .thresh_data_empty_n(thresh_data_empty_n),
    .thresh_data_read(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_thresh_data_read),
    .out_mat_data_din(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_din),
    .out_mat_data_num_data_valid(2'd0),
    .out_mat_data_fifo_cap(2'd0),
    .out_mat_data_full_n(out_mat_data_full_n),
    .out_mat_data_write(grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_write),
    .img_height(img_height_read_reg_61),
    .img_width(img_width_read_reg_56)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_ready == 1'b1)) begin
            grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_height_read_reg_61 <= img_height_dout;
        img_width_read_reg_56 <= img_width_dout;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_height_blk_n = img_height_empty_n;
    end else begin
        img_height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_height_read = 1'b1;
    end else begin
        img_height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_width_blk_n = img_width_empty_n;
    end else begin
        img_width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_width_read = 1'b1;
    end else begin
        img_width_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_mat_data_write = grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_write;
    end else begin
        out_mat_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        thresh_data_read = grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_thresh_data_read;
    end else begin
        thresh_data_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call6 = ((ap_start == 1'b0) | (img_width_empty_n == 1'b0) | (img_height_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start = grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_ap_start_reg;

assign out_mat_data_din = grp_xFMaxSuppressionRad2_8_0_3840_2160_6_0_1_2_2_14_1_2160_s_fu_44_out_mat_data_din;

endmodule //cornerHarris_accel_xFMaxSuppression_8_0_3840_2160_6_0_1_2_2_14_1_s
