// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_cornerHarris_3_3_0_0_3840_2160_1_false_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        grayin_mat_data_dout,
        grayin_mat_data_num_data_valid,
        grayin_mat_data_fifo_cap,
        grayin_mat_data_empty_n,
        grayin_mat_data_read,
        out_mat_data_din,
        out_mat_data_num_data_valid,
        out_mat_data_fifo_cap,
        out_mat_data_full_n,
        out_mat_data_write,
        threshold_dout,
        threshold_num_data_valid,
        threshold_fifo_cap,
        threshold_empty_n,
        threshold_read,
        k_dout,
        k_num_data_valid,
        k_fifo_cap,
        k_empty_n,
        k_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [7:0] grayin_mat_data_dout;
input  [1:0] grayin_mat_data_num_data_valid;
input  [1:0] grayin_mat_data_fifo_cap;
input   grayin_mat_data_empty_n;
output   grayin_mat_data_read;
output  [7:0] out_mat_data_din;
input  [1:0] out_mat_data_num_data_valid;
input  [1:0] out_mat_data_fifo_cap;
input   out_mat_data_full_n;
output   out_mat_data_write;
input  [31:0] threshold_dout;
input  [3:0] threshold_num_data_valid;
input  [3:0] threshold_fifo_cap;
input   threshold_empty_n;
output   threshold_read;
input  [31:0] k_dout;
input  [3:0] k_num_data_valid;
input  [3:0] k_fifo_cap;
input   k_empty_n;
output   k_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg grayin_mat_data_read;
reg out_mat_data_write;
reg threshold_read;
reg k_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    threshold_blk_n;
reg    k_blk_n;
wire   [15:0] img_width_fu_76_p1;
reg   [15:0] img_width_reg_98;
reg    ap_block_state1;
wire   [15:0] img_height_fu_82_p1;
reg   [15:0] img_height_reg_104;
wire   [15:0] trunc_ln125_fu_88_p1;
reg   [15:0] trunc_ln125_reg_110;
wire   [15:0] trunc_ln125_1_fu_93_p1;
reg   [15:0] trunc_ln125_1_reg_115;
wire    grp_xFCornerHarrisDetector_fu_62_grayin_mat_data_read;
wire   [7:0] grp_xFCornerHarrisDetector_fu_62_out_mat_data_din;
wire    grp_xFCornerHarrisDetector_fu_62_out_mat_data_write;
wire    grp_xFCornerHarrisDetector_fu_62_ap_start;
wire    grp_xFCornerHarrisDetector_fu_62_ap_done;
wire    grp_xFCornerHarrisDetector_fu_62_ap_ready;
wire    grp_xFCornerHarrisDetector_fu_62_ap_idle;
reg    grp_xFCornerHarrisDetector_fu_62_ap_continue;
reg    grp_xFCornerHarrisDetector_fu_62_ap_start_reg;
reg    ap_block_state1_ignore_call12;
wire    ap_CS_fsm_state2;
wire    ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_ready;
wire    ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_done;
reg    ap_block_state2_on_subcall_done;
reg    ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready;
reg    ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xFCornerHarrisDetector_fu_62_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready = 1'b0;
#0 ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done = 1'b0;
end

cornerHarris_accel_xFCornerHarrisDetector grp_xFCornerHarrisDetector_fu_62(
    .p_read(img_height_reg_104),
    .p_read1(img_width_reg_98),
    .grayin_mat_data_dout(grayin_mat_data_dout),
    .grayin_mat_data_empty_n(grayin_mat_data_empty_n),
    .grayin_mat_data_read(grp_xFCornerHarrisDetector_fu_62_grayin_mat_data_read),
    .out_mat_data_din(grp_xFCornerHarrisDetector_fu_62_out_mat_data_din),
    .out_mat_data_full_n(out_mat_data_full_n),
    .out_mat_data_write(grp_xFCornerHarrisDetector_fu_62_out_mat_data_write),
    .img_height(img_height_reg_104),
    .img_width(img_width_reg_98),
    .p_threshold(trunc_ln125_reg_110),
    .k(trunc_ln125_1_reg_115),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .img_height_ap_vld(1'b1),
    .img_width_ap_vld(1'b1),
    .p_threshold_ap_vld(1'b1),
    .k_ap_vld(1'b1),
    .ap_start(grp_xFCornerHarrisDetector_fu_62_ap_start),
    .p_read_ap_vld(1'b1),
    .p_read1_ap_vld(1'b1),
    .ap_done(grp_xFCornerHarrisDetector_fu_62_ap_done),
    .ap_ready(grp_xFCornerHarrisDetector_fu_62_ap_ready),
    .ap_idle(grp_xFCornerHarrisDetector_fu_62_ap_idle),
    .ap_continue(grp_xFCornerHarrisDetector_fu_62_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
            ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done <= 1'b0;
        end else if ((grp_xFCornerHarrisDetector_fu_62_ap_done == 1'b1)) begin
            ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
            ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready <= 1'b0;
        end else if ((grp_xFCornerHarrisDetector_fu_62_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFCornerHarrisDetector_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if (((~((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_ready == 1'b0)))) begin
            grp_xFCornerHarrisDetector_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_xFCornerHarrisDetector_fu_62_ap_ready == 1'b1)) begin
            grp_xFCornerHarrisDetector_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_height_reg_104 <= img_height_fu_82_p1;
        img_width_reg_98 <= img_width_fu_76_p1;
        trunc_ln125_1_reg_115 <= trunc_ln125_1_fu_93_p1;
        trunc_ln125_reg_110 <= trunc_ln125_fu_88_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grayin_mat_data_read = grp_xFCornerHarrisDetector_fu_62_grayin_mat_data_read;
    end else begin
        grayin_mat_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        grp_xFCornerHarrisDetector_fu_62_ap_continue = 1'b1;
    end else begin
        grp_xFCornerHarrisDetector_fu_62_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        k_blk_n = k_empty_n;
    end else begin
        k_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        k_read = 1'b1;
    end else begin
        k_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_mat_data_write = grp_xFCornerHarrisDetector_fu_62_out_mat_data_write;
    end else begin
        out_mat_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_blk_n = threshold_empty_n;
    end else begin
        threshold_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_read = 1'b1;
    end else begin
        threshold_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call12 = ((ap_start == 1'b0) | (k_empty_n == 1'b0) | (threshold_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_ready & ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_done) == 1'b0);
end

assign ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_done = (grp_xFCornerHarrisDetector_fu_62_ap_done | ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_done);

assign ap_sync_grp_xFCornerHarrisDetector_fu_62_ap_ready = (grp_xFCornerHarrisDetector_fu_62_ap_ready | ap_sync_reg_grp_xFCornerHarrisDetector_fu_62_ap_ready);

assign grp_xFCornerHarrisDetector_fu_62_ap_start = grp_xFCornerHarrisDetector_fu_62_ap_start_reg;

assign img_height_fu_82_p1 = p_read[15:0];

assign img_width_fu_76_p1 = p_read1[15:0];

assign out_mat_data_din = grp_xFCornerHarrisDetector_fu_62_out_mat_data_din;

assign trunc_ln125_1_fu_93_p1 = k_dout[15:0];

assign trunc_ln125_fu_88_p1 = threshold_dout[15:0];

endmodule //cornerHarris_accel_cornerHarris_3_3_0_0_3840_2160_1_false_2_2_s
