# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/workspace/Gaussianfilter/Gaussianfilter.srcs/sources_1/bd/Gaussianblur_design/ip/Gaussianblur_design_gaussian_filter_accel_0_0/Gaussianblur_design_gaussian_filter_accel_0_0.xci
# IP: The module: 'Gaussianblur_design_gaussian_filter_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/Gaussianfilter/Gaussianfilter.gen/sources_1/bd/Gaussianblur_design/ip/Gaussianblur_design_gaussian_filter_accel_0_0/constraints/gaussian_filter_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Gaussianblur_design_gaussian_filter_accel_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/workspace/Gaussianfilter/Gaussianfilter.srcs/sources_1/bd/Gaussianblur_design/ip/Gaussianblur_design_gaussian_filter_accel_0_0/Gaussianblur_design_gaussian_filter_accel_0_0.xci
# IP: The module: 'Gaussianblur_design_gaussian_filter_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/Gaussianfilter/Gaussianfilter.gen/sources_1/bd/Gaussianblur_design/ip/Gaussianblur_design_gaussian_filter_accel_0_0/constraints/gaussian_filter_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Gaussianblur_design_gaussian_filter_accel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
