# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Gaussianblur_design/Gaussianblur_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design || ORIG_REF_NAME==Gaussianblur_design} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_processing_system7_0_0/Gaussianblur_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_processing_system7_0_0 || ORIG_REF_NAME==Gaussianblur_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_axis_dwidth_converter_0_0/Gaussianblur_design_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_axis_dwidth_converter_0_0 || ORIG_REF_NAME==Gaussianblur_design_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_axis_dwidth_converter_1_0/Gaussianblur_design_axis_dwidth_converter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_axis_dwidth_converter_1_0 || ORIG_REF_NAME==Gaussianblur_design_axis_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_xbar_0/Gaussianblur_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_xbar_0 || ORIG_REF_NAME==Gaussianblur_design_xbar_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_auto_pc_0/Gaussianblur_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_auto_pc_0 || ORIG_REF_NAME==Gaussianblur_design_auto_pc_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_axi_interconnect_0_0/Gaussianblur_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_axi_interconnect_0_0 || ORIG_REF_NAME==Gaussianblur_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_xbar_1/Gaussianblur_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_xbar_1 || ORIG_REF_NAME==Gaussianblur_design_xbar_1} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_auto_us_0/Gaussianblur_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_auto_us_0 || ORIG_REF_NAME==Gaussianblur_design_auto_us_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_auto_us_1/Gaussianblur_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_auto_us_1 || ORIG_REF_NAME==Gaussianblur_design_auto_us_1} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_auto_pc_1/Gaussianblur_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_auto_pc_1 || ORIG_REF_NAME==Gaussianblur_design_auto_pc_1} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_axi_interconnect_1_0/Gaussianblur_design_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_axi_interconnect_1_0 || ORIG_REF_NAME==Gaussianblur_design_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_axi_dma_0_0/Gaussianblur_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_axi_dma_0_0 || ORIG_REF_NAME==Gaussianblur_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_gaussian_filter_accel_0_0/Gaussianblur_design_gaussian_filter_accel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_gaussian_filter_accel_0_0 || ORIG_REF_NAME==Gaussianblur_design_gaussian_filter_accel_0_0} -quiet] -quiet

# IP: bd/Gaussianblur_design/ip/Gaussianblur_design_rst_ps7_0_100M_0/Gaussianblur_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Gaussianblur_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Gaussianblur_design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Xilinx/workspace/Gaussianfilter/Gaussianfilter.gen/sources_1/bd/Gaussianblur_design/Gaussianblur_design_ooc.xdc
